- maven-failsafe-plugin/src/main/java/org/apache/maven/plugin/failsafe/IntegrationTestMojo.java
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/AbstractSurefireMojo.java
- maven-surefire-plugin/src/main/java/org/apache/maven/plugin/surefire/SurefirePlugin.java
- maven-surefire-plugin/src/site/apt/examples/configuring-classpath.apt.vm
- surefire-integration-tests/pom.xml
- surefire-integration-tests/src/test/java/org/apache/maven/surefire/its/fixture/OutputValidator.java
- surefire-integration-tests/src/test/java/org/apache/maven/surefire/its/jiras/Surefire855AllowFailsafeUseArtifactFileIT.java
- surefire-integration-tests/src/test/resources/surefire-855-failsafe-use-bundle/pom.xml
- surefire-integration-tests/src/test/resources/surefire-855-failsafe-use-bundle/src/main/java/pkg/AClassInOSGiBundle.java
- surefire-integration-tests/src/test/resources/surefire-855-failsafe-use-bundle/src/main/resources/main/surefire855.properties
- surefire-integration-tests/src/test/resources/surefire-855-failsafe-use-bundle/src/test/java/jiras/surefre855/bundle/FooIT.java
- surefire-integration-tests/src/test/resources/surefire-855-failsafe-use-bundle/src/test/resources/jiras/surefire855/bundle/properties/surefire855.properties
- surefire-integration-tests/src/test/resources/surefire-855-failsafe-use-jar/pom.xml
- surefire-integration-tests/src/test/resources/surefire-855-failsafe-use-jar/src/main/java/pkg/ToRunJavadoc.java
- surefire-integration-tests/src/test/resources/surefire-855-failsafe-use-jar/src/main/resources/main/surefire855.properties
- surefire-integration-tests/src/test/resources/surefire-855-failsafe-use-jar/src/test/java/jiras/surefire855/jar/FooIT.java
- surefire-integration-tests/src/test/resources/surefire-855-failsafe-use-jar/src/test/resources/jiras/surefire855/jar/properties/surefire855.properties
- surefire-integration-tests/src/test/resources/surefire-855-failsafe-use-war/pom.xml
- surefire-integration-tests/src/test/resources/surefire-855-failsafe-use-war/src/main/java/pkg/ToCreateClassesDirectory.java
- surefire-integration-tests/src/test/resources/surefire-855-failsafe-use-war/src/main/resources/main/surefire855.properties
- surefire-integration-tests/src/test/resources/surefire-855-failsafe-use-war/src/test/java/jiras/surefire855/war/FooIT.java
- surefire-integration-tests/src/test/resources/surefire-855-failsafe-use-war/src/test/resources/jiras/surefire855/war/properties/surefire855.properties
The failsafe-plugin using artifact file instead of target/classes.
> [SUREFIRE-855] Allow failsafe to use actual jar file instead of target/classes

- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/booterclient/ForkConfigurationTest.java
- pom.xml
- surefire-integration-tests/src/test/resources/surefire-1136-cwd-propagation-in-forked-mode/src/test/java/cwd/CurrentWorkingDirectoryInForkedModeTest.java
remove JDK 1.7 API usages in tests, integration test extended to justify deferred directory creation in AbstractSurefireMojo.ensureWorkingDirectoryExists
> SUREFIRE-1136 Current working directory propagation in forked mode

- surefire-integration-tests/src/test/java/org/apache/maven/surefire/its/TestMethodPatternIT.java
- surefire-integration-tests/src/test/java/org/apache/maven/surefire/its/TestMultipleMethodPatternsIT.java
- surefire-integration-tests/src/test/java/org/apache/maven/surefire/its/TestMultipleMethodsIT.java
- surefire-integration-tests/src/test/java/org/apache/maven/surefire/its/TestSingleMethodIT.java
- surefire-integration-tests/src/test/resources/junit48-multiple-method-patterns/pom.xml
- surefire-integration-tests/src/test/resources/junit48-multiple-method-patterns/src/test/java/junit4/BasicTest.java
- surefire-integration-tests/src/test/resources/junit48-multiple-method-patterns/src/test/java/junit4/TestFive.java
- surefire-integration-tests/src/test/resources/junit48-multiple-method-patterns/src/test/java/junit4/TestFour.java
- surefire-integration-tests/src/test/resources/junit48-multiple-method-patterns/src/test/java/junit4/TestThree.java
- surefire-integration-tests/src/test/resources/junit48-multiple-method-patterns/src/test/java/junit4/TestTwo.java
- surefire-integration-tests/src/test/resources/junit48-multiple-methods/pom.xml
- surefire-integration-tests/src/test/resources/junit48-single-method/pom.xml
- surefire-providers/common-junit48/src/main/java/org/apache/maven/surefire/common/junit48/FilterFactory.java
- surefire-providers/common-junit48/src/test/java/org/apache/maven/surefire/common/junit48/FilterFactoryTest.java
This implements a method filter for the junit 4.8 provider that supports the same syntax as discussed in <https://jira.codehaus.org/browse/SUREFIRE-745> and documented in <http://maven.apache.org/surefire/maven-surefire-plugin/examples/single-test.html#Running_a_Set_of_Methods_in_a_Single_Test_Class>. That ticket apparently only contained an implementation for the junit 4.0 provider and only handled one or two methodss per class.
I still have to add tests for this functionality. Would unit tests just for the method filter, using mocked Descriptions, be enough or do you also require integration tests? If so I would need some pointers to how the setup of integration tests inside surefire itself would work.
Let me know what you think of this approach.
> Run individual methods with junit48

- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/AbstractSurefireMojo.java
- surefire-integration-tests/src/test/java/org/apache/maven/surefire/its/jiras/Surefire1053SystemPropertiesIT.java
When you try to set `java.library.path` as a system property in the configuration the plugin emits the warning `java.library.path cannot be set as system property, use <argLine>-Djava.library.path=...<argLine> instead`. This change adds the missing slash in the closing tag which is `<argLine>` but should be `</argLine>`.
> Add missing slash in closing tag of 'use argLine' error message

- surefire-integration-tests/src/test/java/org/apache/maven/surefire/its/JUnit4VersionsIT.java
As discussed in #126 : Pass suffix parameter to unpack method in order to generate separate test workspaces.
> Unpack suffix for parameterized JUnit4VersionsIT

- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/booterclient/ForkStarter.java
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/booterclient/output/ForkClient.java
- maven-surefire-plugin/src/site/apt/examples/shutdown.apt.vm
- maven-surefire-plugin/src/site/fml/faq.fml
- surefire-integration-tests/src/test/java/org/apache/maven/surefire/its/jiras/Surefire1295AttributeJvmCrashesToTestsIT.java
- surefire-integration-tests/src/test/resources/crash-during-test/pom.xml
- surefire-integration-tests/src/test/resources/crash-during-test/src/test/java/junit44/environment/BasicTest.java
- surefire-integration-tests/src/test/resources/crash-during-test/src/test/java/junit44/environment/SomeOtherTest.java
I have 4 tests ATest.java .. DTest.java, and CTest fails like this:
```
@Test
public void x() {
Runtime.getRuntime().halt( 0 );
}
```
Here is the result, see "Crashed tests".
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.2-SNAPSHOT:test (default-test) on project b: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.19.2-SNAPSHOT:test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was cmd.exe /X /C ""D:\Program Files\Java\jdk1.8.0_112\jre\bin\java" -jar D:\vcs\zmaz6\target\surefire\surefirebooter8109843199172464014.jar D:\vcs\zmaz6\target\surefire\surefire4550764212193522341tmp D:\vcs\zmaz6\target\surefire\surefire_07316673656092271862tmp"
[ERROR] Process …
```
> [SUREFIRE-1295] Attribute JVM crashes to tests

- surefire-integration-tests/src/test/java/org/apache/maven/surefire/its/JUnit4VersionsIT.java
- surefire-integration-tests/src/test/java/org/apache/maven/surefire/its/JUnitVersion.java
- surefire-integration-tests/src/test/resources/junit4/pom.xml
- surefire-integration-tests/src/test/resources/junit4/src/test/java/junit5/JUnit5Test.java
First proposal to run tests against multiple JUnit versions.
I implemented an Enum representing the available JUnit versions. The Enum values know how to configure the maven launcher in order to execute tests with that JUnit version. For all 4.x versions this is simply done by setting the junit.version system property. For JUnit 5 and the JUnit 5 vintage support, a profile needs to be activated.
If this i going into the right direction, we can create a parent pom file with the profiles and adopt this to more of the existing tests.
> SUREFIRE-1307: Provide a convenient way to run tests against multiple JUnit versions

- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/booterclient/output/MultipleFailureException.java
We experienced out of memory errors also on Apache Camel with JUnit 4. The reason is probably this infinite loop whenever the `exceptions` Queue contains at least one element.
> SUREFIRE-1382: fixing OutOfMemoryError

- maven-failsafe-plugin/src/main/java/org/apache/maven/plugin/failsafe/IntegrationTestMojo.java
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/AbstractSurefireMojo.java
- maven-surefire-plugin/src/main/java/org/apache/maven/plugin/surefire/SurefirePlugin.java
- surefire-integration-tests/src/test/java/org/apache/maven/surefire/its/jiras/Surefire1396CustomProviderClassPathIT.java
- surefire-integration-tests/src/test/resources/surefire-1396-pluggableproviders-classpath-provider/pom.xml
- surefire-integration-tests/src/test/resources/surefire-1396-pluggableproviders-classpath-provider/src/main/java/org/apache/maven/surefire/testprovider/ClassPathTestProvider.java
- surefire-integration-tests/src/test/resources/surefire-1396-pluggableproviders-classpath-provider/src/main/resources/META-INF/services/org.apache.maven.surefire.providerapi.SurefireProvider
- surefire-integration-tests/src/test/resources/surefire-1396-pluggableproviders-classpath/pom.xml
- surefire-integration-tests/src/test/resources/surefire-1396-pluggableproviders-classpath/src/test/java/pluggableproviders/EmptyIT.java
- surefire-integration-tests/src/test/resources/surefire-1396-pluggableproviders-classpath/src/test/java/pluggableproviders/EmptyTest.java
Hi,
When using a custom Surefire provider with Surefire (not Failsafe), the "provider classpath" contains only the provider and surefire-api. However, when using a custom provider with Failsafe, the provider class path ends up including a lot more... it seems like perhaps all plugins that are loaded? This has caused some mayhem for me when using a custom provider in projects that use a specific version of SLF4J... because then failsafe forces 1.5.6 to be loaded (from this process of incorrectly finding the custom provider), causing a crash.
This PR contains an integration test case showing the bug and a patch to solve it.
> SUREFIRE-1396: Provider class path is incorrect for custom provider in Failsafe

- .gitattributes
- Jenkinsfile
- maven-failsafe-plugin/src/main/java/org/apache/maven/plugin/failsafe/IntegrationTestMojo.java
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/AbstractSurefireMojo.java
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/CommonReflector.java
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/StartupReportConfiguration.java
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/SurefireExecutionParameters.java
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/report/DefaultReporterFactory.java
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/report/FileReporter.java
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/report/NullFileReporter.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/AbstractSurefireMojoJava7PlusTest.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/AbstractSurefireMojoTest.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/booterclient/TestSetMockReporterFactory.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/report/DefaultReporterFactoryTest.java
- maven-surefire-common/src/test/java/org/apache/maven/surefire/report/ConsoleOutputFileReporterTest.java
- maven-surefire-common/src/test/java/org/apache/maven/surefire/report/FileReporterTest.java
- maven-surefire-plugin/src/main/java/org/apache/maven/plugin/surefire/SurefirePlugin.java
- surefire-its/src/test/java/org/apache/maven/surefire/its/UnicodeTestNamesIT.java
- surefire-its/src/test/java/org/apache/maven/surefire/its/fixture/HelperAssertions.java
- surefire-its/src/test/java/org/apache/maven/surefire/its/fixture/OutputValidator.java
- surefire-its/src/test/java/org/apache/maven/surefire/its/fixture/TestFile.java
- surefire-its/src/test/java/org/apache/maven/surefire/its/jiras/Surefire141PluggableProvidersIT.java
- surefire-its/src/test/java/org/apache/maven/surefire/its/jiras/Surefire975DefaultVMEncodingIT.java
- surefire-its/src/test/resources/unicode-testnames/pom.xml
- surefire-providers/surefire-junit47/src/test/java/org/apache/maven/surefire/junitcore/ConcurrentRunListenerTest.java
- surefire-providers/surefire-junit47/src/test/java/org/apache/maven/surefire/junitcore/JUnitCoreTester.java
- surefire-providers/surefire-junit47/src/test/java/org/apache/maven/surefire/junitcore/Surefire746Test.java
Related to JIRA [SUREFIRE-1495](https://issues.apache.org/jira/browse/SUREFIRE-1495).
> [SUREFIRE-1495] Encoding of TXT report file should be configured by ${project.reporting.outputEncoding} and MOJO parameter encoding

- surefire-providers/surefire-junit47/src/main/java/org/apache/maven/surefire/junitcore/JUnitCoreProvider.java
Related to JIRA [SUREFIRE-1498](https://issues.apache.org/jira/browse/SUREFIRE-1498).
> [SUREFIRE-1498] Surefire prints own logs "Couldn't load group class" to native stream.

- surefire-api/src/main/java/org/apache/maven/surefire/util/internal/StringUtils.java
- surefire-api/src/test/java/org/apache/maven/surefire/util/internal/StringUtilsTest.java
Proposed new regression test and accompanying fix for SUREFIRE-1522: https://issues.apache.org/jira/browse/SUREFIRE-1522
The array bounds check now compares off+len to the source length, rather than off to len.
> [SUREFIRE-1522] fix escapeBytesToPrintable bounds check

- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/booterclient/AbstractClasspathForkConfiguration.java
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/booterclient/ForkStarter.java
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/report/StatelessXmlReporter.java
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/report/Utf8RecodingDeferredFileOutputStream.java
- maven-surefire-report-plugin/src/main/java/org/apache/maven/plugins/surefire/report/FailsafeReportMojo.java
- maven-surefire-report-plugin/src/main/java/org/apache/maven/plugins/surefire/report/SurefireReportMojo.java
- pom.xml
- surefire-api/src/main/java/org/apache/maven/surefire/booter/SurefireReflector.java
- surefire-providers/common-junit4/src/main/java/org/apache/maven/surefire/common/junit4/JUnit4Reflector.java
- surefire-providers/surefire-junit47/src/main/java/org/apache/maven/surefire/junitcore/FilteringRequest.java
Current master do not builds!
It's due to incompatibility of checkstyle plugin and couple of checkstyle violations.
I've bumped maven-parent to latest version so plugins are now modern and also fixed those checkstyle violations so that project can be build now.
BTW. Consider to enable CI build. This will prevent this happening in future. There is a `.travis.yml` file already, so :pray:
> Fixing build on master branch

- surefire-its/src/test/java/org/apache/maven/surefire/its/JUnitPlatformStreamCorruptionIT.java
- surefire-its/src/test/resources/surefire-1614-stream-corruption/pom.xml
- surefire-its/src/test/resources/surefire-1614-stream-corruption/src/test/java/com/example/demo/CustomRunner.java
- surefire-its/src/test/resources/surefire-1614-stream-corruption/src/test/java/com/example/demo/SurefireStreamCorruptionTest.java
- surefire-providers/surefire-junit-platform/src/main/java/org/apache/maven/surefire/junitplatform/JUnitPlatformProvider.java
Capture system stream earlier to prevent its corruption.
> Surefire 1614

- .gitignore
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/AbstractSurefireMojo.java
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/util/DependencyScanner.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/util/DependenciesScannerTest.java
- maven-surefire-common/src/test/java/org/apache/maven/surefire/JUnit4SuiteTest.java
- maven-surefire-plugin/src/site/apt/examples/inclusion-exclusion.apt.vm
- maven-surefire-plugin/src/site/fml/faq.fml
- surefire-its/src/test/java/org/apache/maven/surefire/its/jiras/Surefire1004RunTestFromDependencyJarsTypeAndClassifierIT.java
- surefire-its/src/test/resources/surefire-1004-RunTestFromDependencyJarsTypeAndClassifier/pom.xml
- surefire-its/src/test/resources/surefire-1004-RunTestFromDependencyJarsTypeAndClassifier/surefire-1004-module1/pom.xml
- surefire-its/src/test/resources/surefire-1004-RunTestFromDependencyJarsTypeAndClassifier/surefire-1004-module1/src/test/java/org/acme/tests/ClasspathTestA.java
- surefire-its/src/test/resources/surefire-1004-RunTestFromDependencyJarsTypeAndClassifier/surefire-1004-testjar/pom.xml
- surefire-its/src/test/resources/surefire-1004-RunTestFromDependencyJarsTypeAndClassifier/surefire-1004-testjar/src/test/java/org/acme/classifiedtests/ClassifiedTestA.java
- surefire-its/src/test/resources/surefire-1004-RunTestFromDependencyJarsTypeAndClassifier/surefire-1004-testjar/src/test/java/org/acme/othertests/OtherTestA.java
- surefire-its/src/test/resources/surefire-1004-RunTestFromDependencyJarsTypeAndClassifier/surefire-1004-testjar/src/test/java/org/acme/tests/TestA.java
- surefire-its/src/test/resources/surefire-1004-RunTestFromDependencyJarsTypeAndClassifier/surefire-1004-testjar/src/test/java/org/acme/tests/TestB.java
This PR is a rebased version of #173 .
Personally, I am in favor of reusing the logic in `PatternIncludesArtifactFilter` from maven-common-artifact-filters as mentioned in the JIRA description and Robert Scholte's comment https://issues.apache.org/jira/browse/SUREFIRE-1004?focusedCommentId=16324706&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-16324706 That format is more standardized. If you'd like that change to be incorporated, I'm willing to do that as part of this PR.
> [SUREFIRE-1004] Support full gavtc format for dependenciesToScan

- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/AbstractSurefireMojo.java
Added documentation to explicitly state that "none" can be used to disable parallel execution. There was no documentation at the "parallel" parameter before that also listed this special value. The value "none" could only be retrieved from the implementation and is implicitly documented at the description of "parallelTestsTimeoutInSeconds" and "parallelTestsTimeoutForcedInSeconds" in SurefirePlugin.
Knowing a way to disable parallel execution is useful if you need to override a previously parallel exection. We usually declare our surefire tests to be executed in parallel. This is usually defined in the <pluginManagement>-Section of our parent pom.
Nevertheless when execting the tests with Coverage - JaCoCo in our case - the coverage data will be inaccurate if the tests are executed in …
> Improved Documentation for "parallel" parameter value "none"

- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/booterclient/JarManifestForkConfiguration.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/booterclient/JarManifestForkConfigurationTest.java
- maven-surefire-plugin/src/site/apt/examples/cwd.apt.vm
- maven-surefire-plugin/src/site/site.xml
- maven-surefire-report-plugin/pom.xml
- maven-surefire-report-plugin/src/test/java/org/apache/maven/plugins/surefire/report/Surefire597Test.java
- maven-surefire-report-plugin/src/test/java/org/apache/maven/plugins/surefire/report/SurefireSchemaValidationTest.java
- maven-surefire-report-plugin/src/test/java/org/apache/maven/plugins/surefire/report/stubs/SurefireRepMavenProjectStub.java
- maven-surefire-report-plugin/src/test/java/org/apache/maven/plugins/surefire/report/stubs/SurefireRepMavenProjectStub2.java
- surefire-booter/src/main/java/org/apache/maven/surefire/booter/TypeEncodedValue.java
- surefire-its/src/test/java/org/apache/maven/surefire/its/UmlautDirIT.java
- surefire-its/src/test/java/org/apache/maven/surefire/its/fixture/MavenLauncher.java
- surefire-its/src/test/resources/junit-pathWithUmlaut/pom.xml
https://issues.apache.org/jira/browse/SUREFIRE-1617
> [SUREFIRE-1617] Surefire fails with bad message when path contains colon

- maven-surefire-plugin/src/site/apt/examples/junit-platform.apt.vm
- https://issues.apache.org/jira/browse/SUREFIRE-1670
- fix wrong "Filtering by Test Class Names" in failsafe "Using JUnit 5 Platform" page.
> [SUREFIRE-1670] wrong "Filtering by Test Class Names" in failsafe "Using JUnit 5 Platform" page

- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/AbstractSurefireMojo.java
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/ClasspathCache.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/AbstractSurefireMojoTest.java
This PR should fix [SUREFIRE-1679](https://issues.apache.org/jira/browse/SUREFIRE-1679). Once the changes have been reviewed and approved, I'll open another PR to backport them to 2.x.
> [SUREFIRE-1679] Prevent classpath caching from causing pollution

- surefire-providers/surefire-junit-platform/src/main/java/org/apache/maven/surefire/junitplatform/JUnitPlatformProvider.java
- surefire-providers/surefire-junit-platform/src/test/java/org/apache/maven/surefire/junitplatform/JUnitPlatformProviderTest.java
As discussed in [Surefire-1584](https://github.com/apache/maven-surefire/pull/245#issuecomment-543702810) there was a bug where `@DisplayName` would break rerun logic. This PR resolves both this bug and addresses another potential issue _(No triggering sample found though)_ where the `adapter` was treated as if it were stateless, but it is stateful.
The platform provider unit test has been updated with `@DisplayName` usages to verify the correctness of this solution.
> Surefire-1701: Fix @DisplayName breaking reruns

- surefire-providers/surefire-junit-platform/pom.xml
- surefire-providers/surefire-junit-platform/src/main/java/org/apache/maven/surefire/junitplatform/JUnitPlatformProvider.java
- surefire-providers/surefire-junit-platform/src/main/java/org/apache/maven/surefire/junitplatform/RunListenerAdapter.java
- surefire-providers/surefire-junit-platform/src/test/java/org/apache/maven/surefire/junitplatform/JUnitPlatformProviderTest.java
This change fixes the issue discussed in #245 where `@ParameterizedTest` were not supported by the JUnitPlatformProvider.
The fix is rather simple, moving from `DiscoverySelectors.selectMethod` to `DiscoverySelectors.selectUniqueId`. Included are additions to `JUnitPlatformProviderTest` showing this feature is now supported. 
I have detailed why this is a good alternative to parsing the legacy name in a gist: ["The case for UniqueId over Legacy Name "](https://gist.github.com/Col-E/47e0d7cd7267965dada899d4d5e11888)
As mentioned in the gist, using `selectUniqueId` allows us to undo the changes made to [`RunListenerAdapter.toClassMethodName`](https://github.com/apache/maven-surefire/pull/245/files#diff-ad07b0c74885ecb3d687dcc85495e390R240) that were made in #245, which I've also included in …
> [SUREFIRE-1711] Support @ParameterizedTest for JUnit 5 test reruns

- surefire-providers/surefire-junit-platform/src/main/java/org/apache/maven/surefire/junitplatform/JUnitPlatformProvider.java
org.junit.platform.commons.util.StringUtils is an internal API of JUnit
in an internal package (i.e. not exported in the module descriptor).
Thus, Surefire's own `StringUtils` are now used instead.
> Use Surefire's StringUtils instead of JUnit's

- surefire-its/src/test/java/org/apache/maven/surefire/its/JUnitPlatformEnginesIT.java
- surefire-its/src/test/resources/surefire-1727/pom.xml
- surefire-its/src/test/resources/surefire-1727/src/test/java/jira1727/ErrorInTestFactoryJupiterTest.java
- surefire-its/src/test/resources/surefire-1727/src/test/java/jira1727/ErrorInTestProvider.java
- surefire-its/src/test/resources/surefire-1727/src/test/java/jira1727/ErrorInTestTemplateProviderTest.java
- surefire-its/src/test/resources/surefire-1727/src/test/java/jira1727/FailureInTestFactoryJupiterTest.java
- surefire-its/src/test/resources/surefire-1727/src/test/java/jira1727/FailureInTestProvider.java
- surefire-its/src/test/resources/surefire-1727/src/test/java/jira1727/FailureInTestTemplateProviderTest.java
- surefire-its/src/test/resources/surefire-1741/pom.xml
- surefire-its/src/test/resources/surefire-1741/src/test/java/jira1741/ErrorInBeforeAllJupiterTest.java
- surefire-its/src/test/resources/surefire-1741/src/test/java/jira1741/ErrorInParameterizedSourceJupiterTest.java
- surefire-its/src/test/resources/surefire-1741/src/test/java/jira1741/FailureInParameterizedSourceJupiterTest.java
- surefire-providers/surefire-junit-platform/src/main/java/org/apache/maven/surefire/junitplatform/RunListenerAdapter.java
- surefire-providers/surefire-junit-platform/src/test/java/org/apache/maven/surefire/junitplatform/JUnitPlatformProviderTest.java
- surefire-providers/surefire-junit-platform/src/test/java/org/apache/maven/surefire/junitplatform/RunListenerAdapterTest.java
Failed JUnit5 containers will be reported as test failures. This is intended to address [SUREFIRE-1741](https://issues.apache.org/jira/browse/SUREFIRE-1741).
Note: I can't comment on the JIRA issue currently, but I will when I get in to work.
I just now noticed there's already a PR open that (in my opinion) addresses this issue better and more simply (https://github.com/apache/maven-surefire/pull/257), but since I already wrote it up I'm just gonna open this one anyways.
> [SUREFIRE-1741] JUnit5: Detect failed containers

- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/booterclient/output/ForkedChannelDecoder.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/booterclient/output/ForkedChannelDecoderTest.java
- surefire-its/src/test/java/org/apache/maven/surefire/its/JUnitPlatformEnginesIT.java
- surefire-its/src/test/resources/surefire-1748-fail-no-parameters/pom.xml
- surefire-its/src/test/resources/surefire-1748-fail-no-parameters/src/test/java/jira1748/AssertionsFailNoParametersJupiterTest.java
- surefire-its/src/test/resources/surefire-1748/pom.xml
- surefire-its/src/test/resources/surefire-1748/src/test/java/jira1748/AssertionsFailEmptyStringParameterJupiterTest.java
Empty string stack trace messages no longer break the reporting process. This is intended to address [SUREFIRE-1748](https://issues.apache.org/jira/browse/SUREFIRE-1748).
> [SUREFIRE-1748] Fix reporting of empty stack trace messages

- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/AbstractSurefireMojo.java
I add JUnit Platform provider to the documentation for the parameter _groups_ and _excludeGroups_ because these parameters work with it, too.
> [SUREFIRE-1758] JUnit Platform provider isn't mentioned in the docu about groups and excludeGroups

- surefire-providers/surefire-testng/src/main/java/org/apache/maven/surefire/testng/TestNGExecutor.java
instead of org.testng.TestNG.addListener(org.testng.ITestListener) which
has been removed from testng 7.x+ (SUREFIRE-1762)
> use org.testng.TestNG.addListener(java.lang.Object)

- surefire-providers/surefire-testng/src/main/java/org/apache/maven/surefire/testng/TestNGExecutor.java
- address SUREFIRE-1762
- stop using deprecated org.testng.TestNG.addListener(java.lang.Object) as indicated in SUREFIRE-1762 discussion
> Surefire 1762

- surefire-providers/surefire-junit-platform/pom.xml
The JUnit team improved error reporting for engine discovery/execution failures. The relevant changes are in `DefaultLauncher` which is contained in the `junit-platform-launcher` artifact.
This commit upgrades the version to `1.6.1`.
See also https://issues.apache.org/jira/browse/SUREFIRE-1764 and https://github.com/junit-team/junit5/issues/2028
> Upgrade Surefire 2.22.x to junit-platform-launcher 1.6.1

- pom.xml
> update commons compress

- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/AbstractSurefireMojo.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/AbstractSurefireMojoTest.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/AbstractSurefireMojoToolchainsTest.java
When a toolchain is used to select a test jvm, also set the `JAVA_HOME` environment variable to the selected jvm instead of inheriting the environment variable from the invoking shell.
(Note: this PR is based on branch from #287 )
> [SUREFIRE-1783] Fork JVM defined by Toolchain should not inherit JAVA_HOME from Maven process

- maven-surefire-plugin/src/main/java/org/apache/maven/plugin/surefire/SurefirePlugin.java
Somehow, the example code found its way outside of the `<pre><code></code></pre>` block. This commit fixes that.
> Put XML example for "includes" inside its pre tag

- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/extensions/SurefireForkChannel.java
- maven-surefire-common/src/test/java/org/apache/maven/surefire/extensions/ForkChannelTest.java
The first PR:
> I can see two mentioned requests. The first is the default IP adress used to bind the server socket, and the second request is a new configuration with bindAddress.
https://issues.apache.org/jira/browse/SUREFIRE-1800?focusedCommentId=17140020&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17140020
cc @Tibor17
> [SUREFIRE-1800] SurefireForkChannel: use LoopbackAddress

- surefire-booter/src/main/java/org/apache/maven/surefire/booter/spi/LegacyMasterProcessChannelEncoder.java
- surefire-booter/src/test/java/org/apache/maven/surefire/booter/spi/LegacyMasterProcessChannelEncoderTest.java
Added a restoration of thread interrupt state to LegacyMasterProcessChannelEncoder. Added a unit test to ensure this is indeed fixed and not reintroduced.
https://issues.apache.org/jira/projects/SUREFIRE/issues/SUREFIRE-1815
> SUREFIRE-1815: Interrupt state handling in output

- maven-failsafe-plugin/src/main/java/org/apache/maven/plugin/failsafe/IntegrationTestMojo.java
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/AbstractSurefireMojo.java
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/booterclient/BooterSerializer.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/AbstractSurefireMojoJava7PlusTest.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/AbstractSurefireMojoTest.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/MojoMocklessTest.java
- maven-surefire-plugin/src/main/java/org/apache/maven/plugin/surefire/SurefirePlugin.java
- surefire-api/src/main/java/org/apache/maven/surefire/api/testset/RunOrderParameters.java
- surefire-api/src/main/java/org/apache/maven/surefire/api/util/DefaultRunOrderCalculator.java
- surefire-booter/src/main/java/org/apache/maven/surefire/booter/BooterConstants.java
- surefire-booter/src/main/java/org/apache/maven/surefire/booter/BooterDeserializer.java
- surefire-booter/src/main/java/org/apache/maven/surefire/booter/SurefireReflector.java
- surefire-booter/src/test/java/org/apache/maven/surefire/booter/SurefireReflectorTest.java
- surefire-its/src/test/java/org/apache/maven/surefire/its/RunOrderIT.java
- surefire-its/src/test/java/org/apache/maven/surefire/its/fixture/OutputValidator.java
- surefire-its/src/test/java/org/apache/maven/surefire/its/fixture/SurefireLauncher.java
The changes in this pull request addresses issue SUREFIRE-756. Namely, the changes include
- Output of the random seed used to generate a particular random test order when -Dsurefire.runOrder=random or -Dfailsafe.runOrder=random is set
- Ability to replay a previously observed random test order by setting -Dsurefire.seed and -Dfailsafe.seed to the seed that observed the random test order
- Tests to ensure that the setting of the _same_ random seeds do create the _same_ test orders and _different_ random seeds do create _different_ test orders. Note that the inherent randomness of the orders does mean that the tests can be flaky (nondeterministically pass or fail without changes to the code). The current tests have a rate of 0.4% ```(1/3)^5``` of failing. Increasing the number of tests …
> [SUREFIRE-756] Allow ability to capture executed random runOrder for re-play purposes

- surefire-api/src/main/java/org/apache/maven/surefire/api/provider/ProviderParameters.java
- surefire-api/src/main/java/org/apache/maven/surefire/api/util/TestsToRun.java
- surefire-api/src/test/java/org/apache/maven/surefire/api/booter/BaseProviderFactoryTest.java
- surefire-providers/surefire-junit47/pom.xml
- surefire-providers/surefire-junit47/src/main/java/org/apache/maven/surefire/junitcore/JUnitCoreProvider.java
- surefire-providers/surefire-junit47/src/test/java/org/apache/maven/surefire/junitcore/JUnitCoreProviderTest.java
See ticket for details: https://issues.apache.org/jira/browse/SUREFIRE-1842
> [SUREFIRE-1842] - NPE at end of successful test run

- src/site/site.xml
https://issues.apache.org/jira/browse/SUREFIRE-1843 
I think the original author was trying to get these on 2 different lines.  I checked other Maven plugins, everything I saw used a single line. So I just put privacy policy link on the end.
> [SUREFIRE-1843] - Trademarks / privacy policy footer displays broken

- README.md
The Apache logo is only ~300px so scaling to 100% makes it double its native size, on desktop at least, and it becomes pixelated 
Also used code blocks instead of italic text for the run commands
Not sure if PR will show the preview, so if not then you can view it here: https://github.com/michaelboyles/maven-surefire/blob/readme/README.md
> (doc) improved readme

- README.md
Sonatype no longer supports TLSv1.1 and below (effective, June 18th, 2018).
> Update Readme MAVEN_OPTS TLS version

- surefire-providers/common-java5/src/main/java/org/apache/maven/surefire/report/SmartStackTraceParser.java
- surefire-providers/common-java5/src/test/java/org/apache/maven/surefire/report/SmartStackTraceParserTest.java
- surefire-providers/common-java5/src/test/java/org/apache/maven/surefire/report/SomeMockedException.java
JIRA: https://issues.apache.org/jira/browse/SUREFIRE-1851
SmartStackTraceParser is used in various places to parse throwables. However, if the throwable stack trace is null it will throw an NPE itself. This can cause test runners to fail in unexpected ways, which in the worst case can lead to false success test results and passing builds despite the test actually failing.
An exception with a null stacktrace sounds odd, but is easy to do by mocking an exception with frameworks like Mockito. While people probably shouldn't be mocking exceptions, it definitely can and does happen. Can be reproduced with https://github.com/domdomegg/surefire-1851-demo
This is my first PR to the Apache project, apologies if I've gotten anything wrong - I've tried to follow the contributing guidelines as best I …
> [SUREFIRE-1851] Prevent NPE in SmartStackTraceParser

- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/AbstractSurefireMojo.java
- maven-surefire-plugin/src/site/apt/examples/debugging.apt.vm
Using the -Xdebug -Xnoagent -Djava.compiler=NONE causes the OpenJ9 JVM
to run the tests in interpreted mode, thus running them VERY slowly.
In Hotspot JVM these options are ignored.
> Change default debug options to not use legacy options

- maven-surefire-plugin/src/site/apt/examples/rerun-failing-tests.apt.vm
Update example documentation for re-running failing test feature to indicate
that it also works for JUnit 5.x for versions since 3.0.0-M4.
> SUREFIRE-1584: Update example documentation

- maven-surefire-plugin/src/site/markdown/docker.md
sudo, which provides root/ administrator level priviledges on *nix
systems, should be only used when required. Given that docker uses the
kernel of the host system for Linux while docker uses a virtual machine
for Windows/macOS, it is omitted for the latter. This was clarified for
the documentation concerning testing Maven Surefire with docker.
> [SUREFIRE-1840] Distinguish commands in docs for testing with docker

- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/booterclient/ChecksumCalculator.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/booterclient/ChecksumCalculatorTest.java
- maven-surefire-common/src/test/java/org/apache/maven/surefire/JUnit4SuiteTest.java
Two changes:
1) Fix length computation to use bytes, not characters.
2) Use UTF_8 instead of ISO_8859_1 for encoding, because configs can contain
characters that fall outside the ISO_8859_1 character set.
JIRA: https://issues.apache.org/jira/browse/SUREFIRE-1865
> [SUREFIRE-1865] ChecksumCalculator getSha1 does not compute checksums correctly.

- maven-surefire-plugin/src/site/apt/examples/skipping-tests.apt.vm
I found a little error when reading https://maven.apache.org/surefire/maven-failsafe-plugin/examples/skipping-tests.html :
> You can also skip the tests via the command line by executing the following command:
>
>     mvn install -DskipITs
>
> Since skipTests is also supported by the Surefire Plugin, this will have the effect of not running any tests. If, instead, you want to skip only the integration tests being run by the Failsafe Plugin, you would use the skipITs property instead:
>
>     mvn install -DskipITs
The former command should refer to ` skipTests` instead.
> Refer to correct property in skipping-tests doc

- .github/workflows/maven.yml
enable Java build matrix in Github Actions CI.
> ci: JDK 8, JDK 11, JDK 15

- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/extensions/SurefireForkChannel.java
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/report/Utf8RecodingDeferredFileOutputStream.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/extensions/EventConsumerThreadTest.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/extensions/StreamFeederTest.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/report/StatelessXmlReporterTest.java
- surefire-api/src/main/java/org/apache/maven/surefire/api/stream/AbstractStreamDecoder.java
- surefire-api/src/main/java/org/apache/maven/surefire/api/stream/AbstractStreamEncoder.java
- surefire-api/src/main/java/org/apache/maven/surefire/api/util/internal/AbstractNoninterruptibleWritableChannel.java
- surefire-api/src/main/java/org/apache/maven/surefire/api/util/internal/Channels.java
- surefire-api/src/test/java/org/apache/maven/surefire/api/stream/AbstractStreamDecoderTest.java
- surefire-api/src/test/java/org/apache/maven/surefire/api/stream/AbstractStreamEncoderTest.java
- surefire-api/src/test/java/org/apache/maven/surefire/api/util/internal/ChannelsReaderTest.java
- surefire-api/src/test/java/org/apache/maven/surefire/api/util/internal/ChannelsWriterTest.java
- surefire-booter/src/main/java/org/apache/maven/surefire/booter/spi/EventChannelEncoder.java
- surefire-booter/src/test/java/org/apache/maven/surefire/booter/ForkedBooterMockTest.java
- surefire-booter/src/test/java/org/apache/maven/surefire/booter/spi/EventChannelEncoderTest.java
Cast to Buffer to avoid java.lang.NoSuchMethodError due to JDK API
breakage.
This was fixed in a similar way in apache/maven-wagon@92c0d2a.
See mongodb/mongo-java-driver@21c91bd for details.
> [SUREFIRE-1882] Fix failures when compiled on Java 9+ and run on Java 8

- maven-failsafe-plugin/src/main/java/org/apache/maven/plugin/failsafe/VerifyMojo.java
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/AbstractSurefireMojo.java
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/SurefireHelper.java
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/SurefireReportParameters.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/AbstractSurefireMojoTest.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/SurefireHelperTest.java
- maven-surefire-plugin/src/main/java/org/apache/maven/plugin/surefire/SurefirePlugin.java
- maven-surefire-plugin/src/test/java/org/apache/maven/plugin/surefire/SurefirePluginTest.java
- surefire-its/src/test/java/org/apache/maven/surefire/its/JUnitPlatformRerunFailingTestsIT.java
To clarify https://issues.apache.org/jira/browse/SUREFIRE-1878 for further discussion.
> Add failOnFlakeCount option

- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/AbstractSurefireMojo.java
- surefire-its/src/test/java/org/apache/maven/surefire/its/CheckTestNg740ParallelIT.java
- surefire-its/src/test/resources/testng-740-parallel/pom.xml
- surefire-its/src/test/resources/testng-740-parallel/src/test/java/testng740/TestNG740ParallelTest.java
- surefire-providers/surefire-testng/src/main/java/org/apache/maven/surefire/testng/conf/TestNG740Configurator.java
Use reflection to configure parallel arguments,
as the setParallel(String) method has been removed
and the enum equivalent doesn't exist in older
TestNG versions
> [SUREFIRE-1890] Support TestNG 7.4.0

- maven-surefire-plugin/src/site/resources/xsd/surefire-test-report-3.0.xsd
- maven-surefire-report-plugin/src/test/resources/surefire-1894/TEST-surefire.MyTest.xml
This adds the missing version attribute for the `<testsuite/>` element to the schema. As a test, I've just added a copy of the `surefire-597/TEST-surefire.MyTest.xml` with the additional `version="3.0"` attribute in `<testsuite/>`. It will be picked up by the existing `SurefireSchemaValidationTest`. To catch similar errors in the future, a further validation using a freshly created XML report, instead of static ones, would probably be better. However, I'm not familiar enough with the build setup to implement such a check.
> [SUREFIRE-1894] Add missing "version" attribute to report XSD

- surefire-its/src/test/java/org/apache/maven/surefire/its/JUnitPlatformStreamCorruptionIT.java
- surefire-its/src/test/resources/surefire-1659-stream-corruption/pom.xml
- surefire-its/src/test/resources/surefire-1659-stream-corruption/src/test/java/com/example/demo/JUnitPlatformSampleTest.java
- surefire-its/src/test/resources/surefire-1659-stream-corruption/src/test/resources/jul-to-slf4j.properties
- surefire-its/src/test/resources/surefire-1659-stream-corruption/src/test/resources/junit-platform.properties
- surefire-its/src/test/resources/surefire-1659-stream-corruption/src/test/resources/log4j2.xml
- surefire-its/src/test/resources/surefire-1659-stream-corruption/src/test/resources/logback-test.xml
- surefire-providers/surefire-junit-platform/src/main/java/org/apache/maven/surefire/junitplatform/JUnitPlatformProvider.java
- surefire-providers/surefire-junit-platform/src/main/java/org/apache/maven/surefire/junitplatform/LazyLauncher.java
Fix candidate for SUREFIRE-1659
> [SUREFIRE-1659] Log4j logger in TestExecutionListener corrupts Surefire's STDOUT

- maven-surefire-plugin/src/site/apt/examples/testng.apt.vm
> Fix '</plugins>' typo at surefire site

- surefire-its/src/test/java/org/apache/maven/surefire/its/JUnitPlatformEnginesIT.java
- surefire-its/src/test/java/org/apache/maven/surefire/its/jiras/Surefire1914XmlReportingParameterizedTestIT.java
- surefire-its/src/test/resources/surefire-1914-xml-reporting-parameterizedtest/pom.xml
- surefire-its/src/test/resources/surefire-1914-xml-reporting-parameterizedtest/src/test/java/jira1914/ParameterizedDisplayNameTest.java
- surefire-its/src/test/resources/surefire-1914-xml-reporting-parameterizedtest/src/test/java/jira1914/ParameterizedJupiterTest.java
- surefire-providers/surefire-junit-platform/src/main/java/org/apache/maven/surefire/junitplatform/RunListenerAdapter.java
- surefire-providers/surefire-junit-platform/src/test/java/org/apache/maven/surefire/junitplatform/JUnitPlatformProviderTest.java
This is work in progress. It does the job, but may not be the best or most appropriate way to do it.
I'm not particularly happy with the !display.startsWith( "[" ) in the needsSpaceSeparator condition in particular.
> [SUREFIRE-1914] Take displayName of container into account for XML reporting of @ParameterizedTest

- maven-surefire-plugin/src/site/apt/examples/junit.apt.vm
> [site] fixing typo in the junit.apt.vm file

- maven-failsafe-plugin/src/main/java/org/apache/maven/plugin/failsafe/VerifyMojo.java
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/AbstractSurefireMojo.java
- surefire-api/src/main/java/org/apache/maven/surefire/api/report/ReportEntry.java
- surefire-booter/src/main/java/org/apache/maven/surefire/booter/AbstractPathConfiguration.java
- surefire-booter/src/main/java/org/apache/maven/surefire/booter/SystemUtils.java
- surefire-its/src/test/java/org/apache/maven/surefire/its/jiras/Surefire621TestCountingJunit3InParallelIT.java
- surefire-providers/surefire-junit47/src/main/java/org/apache/maven/surefire/junitcore/pc/ParallelComputerBuilder.java
- surefire-providers/surefire-junit47/src/main/java/org/apache/maven/surefire/junitcore/pc/Scheduler.java
- surefire-providers/surefire-junit47/src/main/java/org/apache/maven/surefire/junitcore/pc/SchedulingStrategies.java
- surefire-providers/surefire-junit47/src/main/java/org/apache/maven/surefire/junitcore/pc/SchedulingStrategy.java
- surefire-providers/surefire-junit47/src/main/java/org/apache/maven/surefire/junitcore/pc/ThreadResourcesBalancer.java
When building Surefire with Java 17 (`OpenJDK 64-Bit Server VM Temurin-17+35`) and Maven 3.6.3, the Javadoc generation process fails with the following error:
```
[ERROR] /home/mike/Workspace/maven-surefire/surefire-api/src/main/java/org/apache/maven/surefire/api/report/ReportEntry.java:[79,89] error: tag not supported in HTML5: tt
```
The problem seems not to appear when building the project with Java 11 (`OpenJDK 64-Bit Server VM AdoptOpenJDK`).
As the `<tt>` tag [seems to be deprecated](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/tt), it should probably be replaced with an HTML 5-compatible alternative like `<code>`. This PR introduces such a change.
From the semantical point of view, not every introduced `<code>` usage represents the actual code. In case it's not …
> Replace unsupported <tt> tags in Javadoc comments

- maven-surefire-common/pom.xml
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/AbstractSurefireMojo.java
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/SurefireDependencyResolver.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/AbstractSurefireMojoTest.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/SurefireDependencyResolverTest.java
- pom.xml
> [SUREFIRE-1957] Get rid of maven-artifact-transfer

- .github/dependabot.yml
- .github/workflows/maven-windows-it1.yml
- .github/workflows/maven-windows-it2.yml
- .github/workflows/maven.yml
- .github/workflows/smoketest.yml
- add dependabot and update some github actions
- remove dependabot branches
- fix java version
please …
> Update some github actions and dependabot file

- maven-failsafe-plugin/pom.xml
- maven-surefire-plugin/pom.xml
- maven-surefire-report-plugin/pom.xml
- pom.xml
- bump version by override property mavenPluginToolsVersion
- set Maven core in provided scope
- clean maven-plugin-plugin configuration
--- …
> [SUREFIRE-1968] Bump maven Plugin Tools to 3.6.2

- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/SurefireDependencyResolverTest.java
- pom.xml
> [SUREFIRE-1959] Update plugin (requires Maven 3.2.5+)

- Jenkinsfile
- README.md
- maven-failsafe-plugin/pom.xml
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/AbstractSurefireMojoTest.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/extensions/ConsoleOutputReporterTest.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/extensions/StatelessReporterTest.java
- maven-surefire-common/src/test/java/org/apache/maven/surefire/extensions/StatelessTestsetInfoReporterTest.java
- maven-surefire-plugin/src/site/apt/developing.apt.vm
- pom.xml
- surefire-api/src/test/java/org/apache/maven/surefire/api/stream/AbstractStreamDecoderTest.java
- surefire-its/pom.xml
- surefire-its/src/test/resources/toolchains.xml
- surefire-providers/surefire-junit-platform/pom.xml
> [SUREFIRE-1955] Switch project to Java 8

- Jenkinsfile
We shouldn't deploy artifact from feature branches. 
Branches in more cases have the same version ... so is overridden in repository manager.
--- …
> Deploy artifacts only for master branch

- surefire-booter/src/main/java/org/apache/maven/surefire/booter/Classpath.java
- surefire-booter/src/test/java/org/apache/maven/surefire/booter/ClasspathTest.java
- surefire-booter/src/test/java/org/apache/maven/surefire/booter/IsolatedClassLoaderTest.java
- surefire-booter/src/test/java/org/apache/maven/surefire/booter/NewClassLoaderRunner.java
- surefire-its/src/test/resources/surefire-946-self-destruct-plugin/pom.xml
- surefire-its/src/test/resources/test-helper-dump-pid-plugin/pom.xml
File.toURL() - does not automatically escape illegal characters
--- …
> [SUREFIRE-1869] Replace deprecated File.toURL() by File.toURI().toURL()

- surefire-api/src/main/java/org/apache/maven/surefire/api/util/ReflectionUtils.java
- surefire-api/src/test/java/org/apache/maven/surefire/api/util/ReflectionUtilsTest.java
- surefire-its/src/test/java/org/apache/maven/surefire/its/jiras/Surefire1967CheckTestNgMethodParallelOrderingIT.java
- surefire-its/src/test/resources/surefire-1967-testng-method-parallel-ordering/pom.xml
- surefire-its/src/test/resources/surefire-1967-testng-method-parallel-ordering/src/test/java/testng/parallelOrdering/Base.java
- surefire-its/src/test/resources/surefire-1967-testng-method-parallel-ordering/src/test/java/testng/parallelOrdering/TestClass1.java
- surefire-its/src/test/resources/surefire-1967-testng-method-parallel-ordering/src/test/java/testng/parallelOrdering/TestClass2.java
- surefire-its/src/test/resources/surefire-1967-testng-method-parallel-ordering/src/test/java/testng/parallelOrdering/TestClass3.java
- surefire-its/src/test/resources/surefire-1967-testng-method-parallel-ordering/src/test/java/testng/parallelOrdering/TestClass4.java
- surefire-providers/surefire-testng/src/main/java/org/apache/maven/surefire/testng/TestNGExecutor.java
Before the change, TestNG run from Surefire can execute `@BeforeClass`
on many different test classes/instances, without invoking `@AfterClass`
yet, leading to high resource utilization. This is not observed when
tests are invoked via a suite file. This is because `XmlClass.m_index`
field is used by TestNG to order test execution and this field used not
to be set by Surefire. This commit lets Surefire initialize `XmlClass`
object in a similar manner to how TestNG suite file XML parser does.
where you …
> [SUREFIRE-1967] Fix parallel test ordering to prevent high resource consumption

- .github/workflows/maven-verify.yml
- maven-failsafe-plugin/pom.xml
- maven-surefire-common/pom.xml
- pom.xml
- surefire-api/pom.xml
- surefire-booter/pom.xml
- surefire-booter/src/test/java/org/apache/maven/surefire/booter/NewClassLoaderRunner.java
- surefire-extensions-api/pom.xml
- surefire-its/pom.xml
- surefire-providers/common-java5/pom.xml
- surefire-report-parser/pom.xml
- surefire-shared-utils/pom.xml
> [SUREFIRE-1972] Use current version of surefire-shared-utils

- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/booterclient/DefaultForkConfiguration.java
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/booterclient/output/ThreadedStreamConsumer.java
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/report/StatelessXmlReporter.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/booterclient/ForkConfigurationTest.java
- pom.xml
- surefire-its/src/test/java/org/apache/maven/surefire/its/jiras/Surefire1367AssumptionLogsIT.java
> [SUREFIRE-1937] [SUREFIRE-1938] [SUREFIRE-1980] [SUREFIRE-1981]

- surefire-providers/surefire-junit-platform/src/main/java/org/apache/maven/surefire/junitplatform/JUnitPlatformProvider.java
- surefire-providers/surefire-junit-platform/src/main/java/org/apache/maven/surefire/junitplatform/LazyLauncher.java
A LauncherSession (JUnit Platform 1.8 feature) is started when the Launcher is first used and closed when all tests have run. This allows integrations to run pre and post fixtures.
> [SUREFIRE-1935] Upgrade to JUnit Platform 1.8, start Launcher via LauncherSession

- .github/workflows/maven-verify.yml
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/AbstractSurefireMojo.java
- maven-surefire-plugin/src/site/apt/examples/junit.apt.vm
- surefire-api/src/test/java/org/apache/maven/JUnit4SuiteTest.java
- surefire-api/src/test/java/org/apache/maven/surefire/api/util/internal/ObjectUtilsTest.java
- surefire-booter/src/main/java/org/apache/maven/surefire/booter/ProviderFactory.java
- surefire-booter/src/main/java/org/apache/maven/surefire/booter/SystemUtils.java
- surefire-booter/src/test/java/org/apache/maven/surefire/booter/SystemUtilsTest.java
- surefire-its/src/test/java/org/apache/maven/surefire/its/jiras/Surefire34SecurityManagerIT.java
- surefire-providers/surefire-junit3/src/main/java/org/apache/maven/surefire/junit/JUnit3Provider.java
- surefire-providers/surefire-junit3/src/test/java/org/apache/maven/surefire/junit/JUnitTestSetTest.java
> [SUREFIRE-1975] JDK18 - The Security Manager is deprecated and will be removed in a future release

- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/booterclient/ForkStarter.java
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/booterclient/output/ForkClient.java
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/booterclient/output/NativeStdErrStreamConsumer.java
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/booterclient/output/NativeStdOutStreamConsumer.java
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/extensions/SurefireForkChannel.java
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/log/PluginConsoleLogger.java
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/report/DefaultReporterFactory.java
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/report/ReportsMerger.java
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/report/TestSetRunListener.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/booterclient/ForkStarterTest.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/booterclient/ForkingRunListenerTest.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/booterclient/output/ForkClientTest.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/extensions/E2ETest.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/extensions/EventConsumerThreadTest.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/extensions/ForkedProcessEventNotifierTest.java
- maven-surefire-common/src/test/java/org/apache/maven/surefire/extensions/ForkChannelTest.java
- maven-surefire-common/src/test/java/org/apache/maven/surefire/stream/EventDecoderTest.java
- surefire-api/src/main/java/org/apache/maven/surefire/api/fork/ForkNodeArguments.java
- surefire-api/src/test/java/org/apache/maven/surefire/api/stream/AbstractStreamDecoderTest.java
- surefire-booter/src/main/java/org/apache/maven/surefire/booter/ForkedNodeArg.java
- surefire-booter/src/test/java/org/apache/maven/surefire/booter/spi/CommandChannelDecoderTest.java
The point is to get logger operations in semi-sequential order across multiple threads.
The messages will not be mixed up, especially out and err.
`PluginConsoleLogger` is synchronized. This instance is only one and it is passed to `DefaultReporterFactory` and `TestSetRunListener` as a monitor object.
> [SUREFIRE-1926] Console logs should be synchronized

- surefire-booter/src/main/java/org/apache/maven/surefire/booter/ForkedBooter.java
- surefire-booter/src/main/java/org/apache/maven/surefire/booter/PpidChecker.java
- surefire-booter/src/main/java/org/apache/maven/surefire/booter/ProcessInfo.java
- surefire-booter/src/test/java/org/apache/maven/surefire/booter/ForkedBooterMockTest.java
- surefire-booter/src/test/java/org/apache/maven/surefire/booter/ForkedBooterTest.java
- surefire-booter/src/test/java/org/apache/maven/surefire/booter/PpidCheckerTest.java
> [SUREFIRE-1995] Ping and process checker should use isolated schedulers and the errors should be logged

- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/report/StatelessXmlReporter.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/report/StatelessXmlReporterTest.java
> [SUREFIRE-1556] Test XML file is not valid when rerun "fails" with an assumption

- README.md
- surefire-grouper/pom.xml
This PR addresses the issue in [SUREFIRE-1994] to upgrade/configure `javacc-maven-plugin`.
✅ Each commit in the pull request should have a meaningful subject line and body.
✅ Format the pull request title like `[SUREFIRE-XXX] - Fixes bug in ApproximateQuantiles`
✅ Run `mvn clean install` to make sure basic checks pass.
(I use `mvn clean verify` usually which is the same but does not put artifacts into the local repo.)
✅ I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
> [SUREFIRE-1994] Upgrade javacc-maven-plugin, add setup instructions for Eclipse

- surefire-api/src/main/java/org/apache/maven/surefire/api/report/LegacyPojoStackTraceWriter.java
- surefire-providers/common-java5/src/main/java/org/apache/maven/surefire/report/SmartStackTraceParser.java
- surefire-providers/common-java5/src/test/java/org/apache/maven/surefire/report/ATestClass.java
- surefire-providers/common-java5/src/test/java/org/apache/maven/surefire/report/SmartStackTraceParserTest.java
Pull request for ticket [SUREFIRE-1992] which removes abbreviation of test error/failure messages to 78 characters in two classes that write test results to stdout/stderr.
The fix greatly improves usability of surefire when troubleshooting test failures.
> [SUREFIRE-1992] - Do not abbreviate test error/failure messages to 78 characters

- pom.xml
- surefire-api/src/test/java/org/apache/maven/surefire/api/stream/AbstractStreamDecoderTest.java
> [SUREFIRE-2008] Upgrade animal-sniffer-maven-plugin to 1.21

- surefire-providers/surefire-junit3/src/main/java/org/apache/maven/surefire/junit/JUnit3Provider.java
- surefire-providers/surefire-junit3/src/main/java/org/apache/maven/surefire/junit/JUnitTestSetExecutor.java
- surefire-providers/surefire-junit3/src/main/java/org/apache/maven/surefire/junit/PojoTestSetExecutor.java
- surefire-providers/surefire-junit3/src/main/java/org/apache/maven/surefire/junit/SurefireTestSetExecutor.java
- surefire-providers/surefire-junit3/src/main/java/org/apache/maven/surefire/junit/TestListenerInvocationHandler.java
- surefire-providers/surefire-junit3/src/test/java/org/apache/maven/surefire/junit/JUnitTestSetTest.java
This is a refactoring of surefire-junit3 I needed to do before completing [SUREFIRE-1860](https://issues.apache.org/jira/browse/SUREFIRE-1860). The changes in SUREFIRE-1860 are big and therefore I would like to split them to this refactoring, abstraction in another PR, continue with another PRs regarding implementation of encoder/decoder, SimpleReportEntry. It would give us the opportunity to associate the std/out/err logs with test run id (Thread) and deterministically create the reports and this way fix pending issues (junit5, and simplify the listeners in junit4.7 provider). So I am splitting the work in several pieces.
- [ x] Make sure there is a [JIRA …
> [SUREFIRE-2009] Refactoring of surefire-junit3. JUnitTestSetExecutor and PojoTestSetExecutor should be stateless.

- maven-surefire-report-plugin/pom.xml
- pom.xml
- surefire-its/src/test/resources/surefire-1490/pom.xml
- [x ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/SUREFIRE) filed 
- [ x] Each commit in the pull request should have a meaningful subject line and body.
- [x ] Format the pull request title like `[SUREFIRE-XXX] - Fixes bug in ApproximateQuantiles`,
- [x ] Write a pull request description that is …
> [SUREFIRE-2003] Upgrade Maven Reporting to 3.1.0

- .editorconfig
- maven-surefire-report-plugin/pom.xml
- surefire-report-parser/pom.xml
- surefire-report-parser/src/main/java/org/apache/maven/plugins/surefire/report/ReportTestCase.java
- surefire-report-parser/src/main/java/org/apache/maven/plugins/surefire/report/SurefireReportParser.java
- surefire-report-parser/src/main/java/org/apache/maven/plugins/surefire/report/TestSuiteXmlParser.java
- [x ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/SUREFIRE) filed 
- [x ] Each commit in the pull request should have a meaningful subject line and body.
- [x ] Format the pull request title like `[SUREFIRE-XXX] - Fixes bug in ApproximateQuantiles`,
- [x ] Write a pull request description that is …
> [SUREFIRE-2012] Use maven-shared-utils instead of surefire-shared-utils in Report Parser. Removed commons-lang in Report Plugin.

- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/booterclient/ModularClasspathForkConfiguration.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/booterclient/ModularClasspathForkConfigurationTest.java
- surefire-its/src/test/java/org/apache/maven/surefire/its/Junit5ModulePathIT.java
- surefire-its/src/test/resources/junit5-modulepath/pom.xml
- surefire-its/src/test/resources/junit5-modulepath/src/main/java/com/app/Main.java
- surefire-its/src/test/resources/junit5-modulepath/src/main/java/module-info.java
- surefire-its/src/test/resources/junit5-modulepath/src/test/java/com/app/AppTest.java
This PR fixes : https://issues.apache.org/jira/browse/SUREFIRE-1909
We decided to go with the drop in replacement of `--add-exports` with `--add-opens`, as suggested in the issue.
To add to the background of this issue, a previous PR has been created, introducing the option to use either `add-exports` or `add-opens`, the PR is still accessible here : https://github.com/apache/maven-surefire/pull/461
> [SUREFIRE-1909] -  Support JUnit 5 reflection access by changing add-exports to add-opens

- maven-surefire-plugin/src/site/apt/developing.apt.vm
The folder `surefire-integration-tests` has been renamed to `surefire-its`. This should corrected in the documentation.
Since this is like a typo, I did not create a ticket.
- [x Run `mvn clean install` to make sure basic checks pass. A more thorough check will 
To make clear …
> Fix documentation: integration tests are in surefire-its now

- surefire-its/src/test/java/org/apache/maven/surefire/its/jiras/Surefire1787JUnit5IT.java
- surefire-its/src/test/resources/junit5-runner/src/test/java/examples/RootTest.java
- surefire-its/src/test/resources/junit5-runner/src/test/java/examples/a/ATest.java
- surefire-its/src/test/resources/junit5-runner/src/test/java/examples/b/BTest.java
> [SUREFIRE-2026] Improve assertions in Surefire1787JUnit5IT

- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/booterclient/output/ForkClient.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/extensions/ForkedProcessEventNotifierTest.java
- surefire-api/src/main/java/org/apache/maven/surefire/api/booter/ForkingRunListener.java
- surefire-api/src/main/java/org/apache/maven/surefire/api/booter/MasterProcessChannelEncoder.java
- surefire-booter/src/main/java/org/apache/maven/surefire/booter/spi/EventChannelEncoder.java
- surefire-booter/src/test/java/org/apache/maven/surefire/booter/spi/EventChannelEncoderTest.java
> [SUREFIRE-2025] Updated abstractions which helps associating systemProperties() with a test

- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/AbstractSurefireMojo.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/AbstractSurefireMojoTest.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/MojoMocklessTest.java
- maven-surefire-plugin/src/main/java/org/apache/maven/plugin/surefire/SurefirePlugin.java
- surefire-its/src/test/java/org/apache/maven/surefire/its/AbstractTestMultipleMethodPatterns.java
- surefire-its/src/test/java/org/apache/maven/surefire/its/jiras/Surefire1964IT.java
- surefire-its/src/test/resources/surefire-1964/exclusions.txt
- surefire-its/src/test/resources/surefire-1964/inclusions.txt
- surefire-its/src/test/resources/surefire-1964/pom.xml
- surefire-its/src/test/resources/surefire-1964/src/test/java/pkg/ExcludedTest.java
- surefire-its/src/test/resources/surefire-1964/src/test/java/pkg/FilterTest.java
> [SUREFIRE-1964] Support for method filtering on excludesFile and includesFile

- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/AbstractSurefireMojo.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/AbstractSurefireMojoJava7PlusTest.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/AbstractSurefireMojoTest.java
- surefire-its/src/test/java/org/apache/maven/surefire/its/jiras/Surefire2036IT.java
- surefire-its/src/test/resources/surefire-2036/pom.xml
- surefire-its/src/test/resources/surefire-2036/src/test/java/pkg/JUnit4Test.java
- surefire-its/src/test/resources/surefire-2036/src/test/java/pkg/JUnit5Test.java
Modified getJUnit5Artifact() to care _only_ about JUnit 5 artifacts
Added getJUnitPlatformRunnerArtifact() to care about the JUnit Platform Runner artifact
JUnitPlatformProviderInfo is enabled by default based on a combination of above
Avoids NullPointerException when explicitly configured provider needs to know the available JUnit5 artifact
is to use the JIRA issue title in the pull request title and in the first line of the …
> [SUREFIRE-2036] Fix JUnit 5 with configured provider

- .github/workflows/maven-verify.yml
- maven-surefire-common/pom.xml
- maven-surefire-plugin/pom.xml
- maven-surefire-report-plugin/pom.xml
- pom.xml
- surefire-its/pom.xml
> [SUREFIRE-2038] Upgrade Maven Parent to 35

- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/SurefireHelper.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/AbstractSurefireMojoTest.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/SurefireHelperTest.java
- surefire-its/src/test/java/org/apache/maven/surefire/its/jiras/Surefire1426JvmCrashShouldNotBeIgnoredIT.java
- surefire-its/src/test/resources/surefire-1426-ignore-fail-jvm-crash/pom.xml
- surefire-its/src/test/resources/surefire-1426-ignore-fail-jvm-crash/src/test/java/PojoTest.java
I am focusing on the only class SurefireHelper and unit tests.
The integration test can be taken from #478 .
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are …
> [SUREFIRE-1426] Fork crash doesn't fail build with -Dmaven.test.failure.ignore=true

- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/booterclient/output/ForkClient.java
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/booterclient/output/ForkedProcessEventNotifier.java
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/booterclient/output/ForkedProcessPropertyEventListener.java
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/booterclient/output/ForkedProcessStandardOutErrEventListener.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/extensions/ForkedProcessEventNotifierTest.java
The issue is SUREFIRE-1860 is a parent 6 child issues.
I forgot to update two listeners out of three which belong to handlers of test specifics.
`ForkedProcessReportEventListener` was updated in SUREFIRE-2014 but the other two (ForkedProcessPropertyEventListener and ForkedProcessStandardOutErrEventListener) were missed.
be …
> [SUREFIRE-2046] Resolved TODOs. Updated callbacks ForkedProcessPropertyEventListener and ForkedProcessStandardOutErrEventListener.

- maven-surefire-plugin/src/site/apt/examples/junit-platform.apt.vm
- surefire-its/src/test/java/org/apache/maven/surefire/its/jiras/Surefire1787JUnit5IT.java
- surefire-its/src/test/resources/junit5-suite/pom.xml
- surefire-its/src/test/resources/junit5-suite/src/test/java/pkg/JUnit5Tests.java
- surefire-its/src/test/resources/junit5-suite/src/test/java/pkg/domain/AxTest.java
- surefire-its/src/test/resources/junit5-suite/src/test/java/pkg/domain/BxTest.java
- surefire-providers/surefire-junit-platform/src/main/java/org/apache/maven/surefire/junitplatform/JUnitPlatformProvider.java
- surefire-providers/surefire-junit-platform/src/test/java/org/apache/maven/surefire/junitplatform/JUnitPlatformProviderTest.java
Following this checklist to help us incorporate your contribution quickly and easily:
the [Apache …
> [SUREFIRE-2040] No tests executed with junit-platform-suite and -Dtest=TestSuite

- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/AbstractSurefireMojo.java
- surefire-its/src/test/resources/surefire-818-ignored-tests-on-npe/pom.xml
A simple change in the behavior, by user group request, changing the default value for `trimStackTrace` from true to false.
Backporting the improvement SUREFIRE-1432 (8a6b33453d3114e755ad9f0776bd8f5ca7bf3bc0) from the branch origin/release/3.0.0-M6 to origin/master.
If your pull …
> [SUREFIRE-1432] trimStackTrace = false by default

- maven-surefire-plugin/src/site/apt/examples/junit-platform.apt.vm
- surefire-its/src/test/java/org/apache/maven/surefire/its/jiras/Surefire1787JUnit5IT.java
- surefire-its/src/test/resources/junit5-testng/pom.xml
- surefire-its/src/test/resources/junit5-testng/src/test/java/pkg/JUnit5Test.java
> [SUREFIRE-2024] Replace testng-junit5 by testng-engine

- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/AbstractSurefireMojo.java
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/SurefireDependencyResolver.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/AbstractSurefireMojoTest.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/SurefireDependencyResolverTest.java
Surefire doesn't propagate the exception during artifact resolution, and then later, it fails with a `NullPointerException` when it needs to access the artifact (in `AbstractSurefireMojo.java#L4125` or `SurefireDependencyResolver.java#L203`). This makes harder to understand the underlying issue. This change uses `ResolutionErrorHandler` to propagate the actual issue.
---
is to use the JIRA issue title in the pull request title …
> [SUREFIRE-2051] Propagate exceptions while resolving artifacts in `SurefireDependencyResolver`

- pom.xml
- surefire-its/src/test/java/org/apache/maven/surefire/its/fixture/MavenLauncher.java
- surefire-its/src/test/java/org/apache/maven/surefire/its/jiras/Surefire772NoFailsafeReportsIT.java
> [SUREFIRE-2044] Upgrade Maven Verifier to 1.8.0

- surefire-booter/src/main/java/org/apache/maven/surefire/booter/spi/EventChannelEncoder.java
- surefire-booter/src/test/java/org/apache/maven/surefire/booter/spi/EventChannelEncoderTest.java
See https://issues.apache.org/jira/browse/SUREFIRE-2056 for an analysis of the problem.
This brings the buffer size back in line with what `encodeHeader` actually does, thereby avoiding a buffer overflow.
-----  …
> SUREFIRE-2056 BufferOverflowException when encoding message with null testId

- README.md
- surefire-its/src/test/java/org/apache/maven/surefire/its/CheckTestNg740ParallelIT.java
- surefire-its/src/test/java/org/apache/maven/surefire/its/CheckTestNgListenerReporterIT.java
- surefire-its/src/test/java/org/apache/maven/surefire/its/JUnit47RerunFailingTestWithCucumberIT.java
- surefire-its/src/test/java/org/apache/maven/surefire/its/JUnit47WithCucumberIT.java
- surefire-its/src/test/java/org/apache/maven/surefire/its/JUnitPlatformEnginesIT.java
- surefire-its/src/test/java/org/apache/maven/surefire/its/JUnitPlatformIT.java
- surefire-its/src/test/java/org/apache/maven/surefire/its/JUnitPlatformRerunFailingTestsIT.java
- surefire-its/src/test/java/org/apache/maven/surefire/its/JUnitPlatformStreamCorruptionIT.java
- surefire-its/src/test/java/org/apache/maven/surefire/its/RunOrderIT.java
- surefire-its/src/test/java/org/apache/maven/surefire/its/fixture/SurefireJUnit4IntegrationTestCase.java
- surefire-its/src/test/java/org/apache/maven/surefire/its/fixture/SurefireLauncher.java
- surefire-its/src/test/java/org/apache/maven/surefire/its/fixture/SurefireLauncherTest.java
- surefire-its/src/test/java/org/apache/maven/surefire/its/jiras/SpockIT.java
- surefire-its/src/test/java/org/apache/maven/surefire/its/jiras/Surefire1585IT.java
- surefire-its/src/test/java/org/apache/maven/surefire/its/jiras/Surefire1914XmlReportingParameterizedTestIT.java
- surefire-its/src/test/java/org/apache/maven/surefire/its/jiras/Surefire260TestWithIdenticalNamesIT.java
- surefire-its/src/test/java/org/apache/maven/surefire/its/jiras/Surefire673MockitoIT.java
> [SUREFIRE-2062] Remove code corresponding to jdk 7 from IT tests

- surefire-providers/surefire-testng/src/main/java/org/apache/maven/surefire/testng/conf/TestNG740Configurator.java
- surefire-providers/surefire-testng/src/main/java/org/apache/maven/surefire/testng/conf/TestNGMapConfigurator.java
This pull request revises the handling of the TestNG 7.4+ [parallel] option so that it accepts all valid values.
Following this checklist to help us incorporate your contribution quickly and easily:
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you …
> [SUREFIRE-2064] Allow all supported values of [parallel] option

- surefire-api/src/main/java/org/apache/maven/surefire/api/stream/AbstractStreamDecoder.java
- surefire-api/src/test/java/org/apache/maven/surefire/api/stream/AbstractStreamDecoderTest.java
Two cases are covered here:
* Test run swallowing some of the outputs and finishing with the following warning:
```
[WARNING] Corrupted channel by directly writing to native stream in forked JVM 1. 
```
* Test run getting completely stuck
Both cases are caused by the same issue, output buffer overflow in [AbstractStreamDecoder#readString(Memento, int)](https://github.com/apache/maven-surefire/blob/master/surefire-api/src/main/java/org/apache/maven/surefire/api/stream/AbstractStreamDecoder.java#L302), because output char buffer is not cleared if it's not completely full.
Added unit tests:
* AbstractStreamDecoderTest#shouldReadStringOverflowOnNewLine:
Input buffer of 1026 bytes: 1023 x 1-byte + 1 x 2-bytes encoded character + new line (LF). 
* In first iteration it decodes the first 1023 …
> [SUREFIRE-2058] Corrupted STDOUT by directly writing to native stream in forked JVM 1 with UTF-8 console logging

- surefire-api/src/main/java/org/apache/maven/surefire/api/stream/AbstractStreamEncoder.java
- surefire-api/src/test/java/org/apache/maven/surefire/api/stream/AbstractStreamEncoderTest.java
- surefire-booter/src/main/java/org/apache/maven/surefire/booter/spi/EventChannelEncoder.java
- surefire-booter/src/test/java/org/apache/maven/surefire/booter/spi/EventChannelEncoderTest.java
Per @Tibor17's comment https://github.com/apache/maven-surefire/pull/518#issuecomment-1099706229 and https://github.com/apache/maven-surefire/pull/518#issuecomment-1108371215 
and after some dicsussion (see comment after https://github.com/apache/maven-surefire/pull/518#issuecomment-1099706229) pulled this into a separate issue.
Jira ticket: https://issues.apache.org/jira/browse/SUREFIRE-2076
[AbstractStreamEncoder#encodeHeader](https://github.com/apache/maven-surefire/blob/959c1e9cabb8d06c72f5ebd7eb6e56e9987eccf8/surefire-api/src/main/java/org/apache/maven/surefire/api/stream/AbstractStreamEncoder.java#L86) stores runMode part in at least 3 bytes:
- 1 byte for length
- 1 byte delimiter
- runMode content in length-bytes
- 1 byte delimiter 
In case of null runMode the encoded part becomes …
> [SUREFIRE-2076] BufferOverflowException when encoding message with null runMode

- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/AbstractSurefireMojo.java
- surefire-api/src/main/java/org/apache/maven/surefire/api/util/DefaultRunOrderCalculator.java
- surefire-its/src/test/java/org/apache/maven/surefire/its/RunOrderIT.java
Always show the random seed when using the random runOrder. This is so tests that fail because of their runOrder can be replayed without necessarily knowing the build command.
> [SUREFIRE-2055] Always show random seed

- surefire-shared-utils/pom.xml
This small PR removes redundant configuration from maven-shade-plugin in `surefire-shared-utils`.
Following this checklist to help us incorporate your contribution quickly and easily: …
> [SUREFIRE-2083] - Remove redundant config from maven-shade-plugin

- surefire-its/src/test/resources/testng-740-parallel-without-threadcount/pom.xml
- surefire-its/src/test/resources/testng-740-parallel-without-threadcount/src/test/java/testng740/TestNG740ParallelTest.java
- surefire-providers/surefire-testng/src/main/java/org/apache/maven/surefire/testng/conf/TestNGMapConfigurator.java
> [SUREFIRE-2075] Only set thread count if specified in configuration

- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/booterclient/DefaultForkConfiguration.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/booterclient/DefaultForkConfigurationTest.java
[**SUREFIRE-2077**](https://issues.apache.org/jira/browse/SUREFIRE-2077)
please ask on the developers …
> [SUREFIRE-2077] Allow consecutive spaces in argLine

- maven-surefire-plugin/src/site/apt/history.apt.vm
- maven-surefire-plugin/src/site/apt/index.apt.vm
- maven-surefire-plugin/src/site/site.xml
> move this version changelog to a dedicated page

- src/site/site.xml
- use banners from parent pom
- use maven-fluido-skin version from parent
- tob/side bar configuration from parent
- remove dead link to privacy
--- …
> [SUREFIRE-2067] Improve site configuration

- maven-failsafe-plugin/src/test/java/org/apache/maven/plugin/failsafe/MarshallerUnmarshallerTest.java
- maven-failsafe-plugin/src/test/java/org/apache/maven/plugin/failsafe/RunResultTest.java
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/booterclient/JarManifestForkConfiguration.java
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/booterclient/ModularClasspathForkConfiguration.java
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/report/Utf8RecodingDeferredFileOutputStream.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/AbstractSurefireMojoTest.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/MojoMocklessTest.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/booterclient/ModularClasspathForkConfigurationTest.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/runorder/RunEntryStatisticsMapTest.java
- surefire-api/src/main/java/org/apache/maven/surefire/api/util/SureFireFileManager.java
- surefire-api/src/main/java/org/apache/maven/surefire/api/util/TempFileManager.java
- surefire-api/src/test/java/org/apache/maven/surefire/api/util/TempFileManagerTest.java
- surefire-booter/src/main/java/org/apache/maven/surefire/booter/PpidChecker.java
- surefire-booter/src/main/java/org/apache/maven/surefire/booter/SystemPropertyManager.java
- surefire-booter/src/test/java/org/apache/maven/surefire/booter/ForkedBooterTest.java
Management of temporary files in surefire into sub directories of the system's directory of temporary files to avoid bloating the temp directory root.
To …
> [SUREFIRE-2086] Management of temporary files

- maven-surefire-report-plugin/src/main/java/org/apache/maven/plugins/surefire/report/SurefireReportGenerator.java
- maven-surefire-report-plugin/src/test/java/org/apache/maven/plugins/surefire/report/SurefireReportMojoTest.java
Hi there,
last December Karl Heinz Marbaise showed me the "up for grabs" JIRA issues. Thanks again Karl Heinz! Unfortunately it took me much longer than expected. 
Anyway, here is a tiny contribution on my behalf. This fixes [SUREFIRE-2090](https://issues.apache.org/jira/browse/SUREFIRE-2090). The fix was more more less stated in the comments by Michael Osipov. I added the 'L' and updated the test cases in `SurefireReportMojoTest`. I also made sure it works in a pet project of mine.
Since this is my first contribution to Apache Maven I am unaware if I did everything according to the conventions. I am unsure where to communicate: the dev mailing, JIRA or here at GitHub. I will leave a comment pointing to this PR in the JIRA issue.
> [SUREFIRE-2090] - Xref link to source code with specified line number doesn't work. Missing "L" in anchor

- surefire-booter/src/main/java/org/apache/maven/surefire/booter/PpidChecker.java
- surefire-booter/src/test/java/org/apache/maven/surefire/booter/PpidCheckerTest.java
- Use the value of the system property native.encoding as charset for parsing the output of the ps command that ForkedBooter issues on Unix-like OSes when checking if the forked process is still alive
- Fall back to UTF-8 in case the system property is absent (pre-JDK17)
- Remove an unnecessary System.out.println in a test that was probably committed by accident
This fixes the ConsoleOutputIT on Java 18 and above.
is to use the …
> [SUREFIRE-2135] Use native.encoding for parsing ps

- surefire-providers/surefire-junit-platform/src/main/java/org/apache/maven/surefire/junitplatform/RunListenerAdapter.java
- surefire-providers/surefire-junit-platform/src/test/java/org/apache/maven/surefire/junitplatform/RunListenerAdapterTest.java
This is a fix for http://issues.apache.org/jira/browse/SUREFIRE-2032, which cause a display issue with https://github.com/apache/maven-integration-testing/pull/176.
> [SUREFIRE-2032] Fix test count when using @Disabled at class level

- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/report/WrappedReportEntry.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/report/WrappedReportEntryTest.java
- surefire-api/src/main/java/org/apache/maven/surefire/api/report/CategorizedReportEntry.java
- surefire-api/src/main/java/org/apache/maven/surefire/api/report/ReportEntry.java
- surefire-api/src/test/java/org/apache/maven/surefire/api/report/CategorizedReportEntryTest.java
When phrased test names are enabled, but an annotation such as DisplayName
in JUnit5 is missing from the test, the output to the console will now
fall back to using the original name rather than naming the test
'null'.
This amends this behaviour to provide a more meaningful name in these scenarios,
which can be important when migrating a large code base over to using 
phrased names incrementally.
An example of the existing output which can be problematic:
----
> [SUREFIRE-2101] - Fixes 'null' phrased test names with JUnit5 without @DisplayName

- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/report/TestSetStats.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/report/TestSetStatsTest.java
- surefire-its/src/test/java/org/apache/maven/surefire/its/JUnitPlatformEnginesIT.java
If phrased console reporting is active, but no @DisplayName annotation is set, fall back to using the class name in console output …
> [SUREFIRE-2101] JUnit5 console reporting: Fall back to class name

- .github/workflows/maven-verify.yml
- Jenkinsfile
- pom.xml
> [SUREFIRE-2139] Raise plexus-java to 1.1.2 for proper Java 19/20 bytecode support

- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/AbstractSurefireMojoJunitCoreProvidersInfoTest.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/AbstractSurefireMojoProvidersInfoTest.java
- maven-surefire-common/src/test/java/org/apache/maven/surefire/JUnit4SuiteTest.java
> [SUREFIRE-1962] Unit test for ProviderInfo#isApplicable

- surefire-api/src/main/java/org/apache/maven/surefire/api/util/SureFireFileManager.java
- surefire-api/src/test/java/org/apache/maven/surefire/api/util/SureFireFileManagerTest.java
This pull request offers a fix for bug [SUREFIRE-2109].
Following this checklist to help us incorporate your contribution quickly and easily:
To make …
> [SUREFIRE-2109] Add suffix derived from current user to Surefire temp directory name

- maven-failsafe-plugin/src/main/java/org/apache/maven/plugin/failsafe/VerifyMojo.java
- maven-failsafe-plugin/src/test/java/org/apache/maven/plugin/failsafe/VerifyMojoTest.java
- maven-failsafe-plugin/src/test/resources/verify-mojo/failsafe-summary-booter-fork-error.xml
- maven-failsafe-plugin/src/test/resources/verify-mojo/failsafe-summary-success.xml
- surefire-its/src/test/java/org/apache/maven/surefire/its/jiras/Surefire2095FailsafeJvmCrashShouldNotBeIgnoredIT.java
- surefire-its/src/test/resources/surefire-2095-failsafe-jvm-crash/pom.xml
- surefire-its/src/test/resources/surefire-2095-failsafe-jvm-crash/src/test/java/PojoIT.java
When `maven.test.failure.ignore` is enabled, a test that crashes the JVM (e.g. that causes an OOM, with `-XX:+CrashOnOutOfMemoryError`) currently does not cause a build failure. This is perhaps the right behavior but is an issue in a CI setting because the following:
1) No failsafe-reports/TEST-*.xml file is created that corresponds to the test that crashed.
2) No failsafe-reports/TEST-*.xml files are created for all the tests that did not run (because they were to run after the crashed test in that same forked process).
Because of that, in a Jenkins setting, the Jenkins Junit plugin does not identify any test failures and the build is marked successful instead of unstable. The forked process crash is only identified in the failsafe-summary XML (in the failureMessage) which AFAIK the …
> [SUREFIRE-2095] Fork crash doesn't fail build with -Dmaven.test.failure.ignore=true when run with failsafe

- surefire-its/src/test/java/org/apache/maven/surefire/its/fixture/TestFile.java
- surefire-its/src/test/java/org/apache/maven/surefire/its/jiras/Surefire2065IT.java
- surefire-its/src/test/resources/surefire-2065-common/pom.xml
- surefire-its/src/test/resources/surefire-2065-common/src/test/java/pkg/junit4/ParameterizedTest.java
- surefire-its/src/test/resources/surefire-2065-common/src/test/java/pkg/junit4/ParameterizedWithDisplayNameTest.java
- surefire-its/src/test/resources/surefire-2065-common/src/test/java/pkg/junit5/ParameterizedTest.java
- surefire-its/src/test/resources/surefire-2065-common/src/test/java/pkg/junit5/ParameterizedWithDisplayNameTest.java
- surefire-its/src/test/resources/surefire-2065-junit4/pom.xml
- surefire-its/src/test/resources/surefire-2065-junit4/src/test/java/pkg/junit4/ParameterizedTest.java
- surefire-its/src/test/resources/surefire-2065-junit4/src/test/java/pkg/junit4/ParameterizedWithDisplayNameTest.java
- surefire-its/src/test/resources/surefire-2065-junit5/pom.xml
- surefire-its/src/test/resources/surefire-2065-junit5/src/test/java/pkg/junit5/ParameterizedTest.java
- surefire-its/src/test/resources/surefire-2065-junit5/src/test/java/pkg/junit5/ParameterizedWithDisplayNameTest.java
- surefire-providers/surefire-junit-platform/src/main/java/org/apache/maven/surefire/junitplatform/RunListenerAdapter.java
This is an adjusted PR based on #516 from chalmagr.
I kept the additional ITs exactly as written by chalmagr. 
The fix itself is different. It's less invasive, doesn't require making changes to the expectations of any expecting tests or ITs.
The root cause of the bug is that the logic for determining `hasParams` only looks at `methodSource.getMethodParameterTypes()`. That's not correct for JUnit 4 Parameterized tests since they do not have a method parameter. In JUnit 4 the parameterization is handled on a level further up.
The fix corrects the logic for determining `hasParams` so that it also works for JUnit4. It relies on the fact that for JUnit 4 parameterized tests there is a container-type test identifier with the legacyReportingName `[<index>]` or `[<displayName>]` that has an empty …
> [SUREFIRE-2065] Fix parameterized JUnit4 test reporting

- surefire-its/src/test/java/org/apache/maven/surefire/its/jiras/Surefire2032NestedSkippedIT.java
- surefire-its/src/test/java/org/apache/maven/surefire/its/jiras/Surefire2143ParameterizedSkippedIT.java
- surefire-its/src/test/resources/surefire-2032-nested-test-class-skipped/pom.xml
- surefire-its/src/test/resources/surefire-2032-nested-test-class-skipped/src/test/java/jira2032/DisabledNestedTest.java
- surefire-its/src/test/resources/surefire-2143-junit4-parameterized-test-skipped/pom.xml
- surefire-its/src/test/resources/surefire-2143-junit4-parameterized-test-skipped/src/test/java/jira2143/IgnoredParameterizedTest.java
- surefire-its/src/test/resources/surefire-2143-junit5-parameterized-test-skipped/pom.xml
- surefire-its/src/test/resources/surefire-2143-junit5-parameterized-test-skipped/src/test/java/jira2143/DisabledParameterizedTest.java
- surefire-providers/surefire-junit-platform/src/main/java/org/apache/maven/surefire/junitplatform/RunListenerAdapter.java
- surefire-providers/surefire-junit-platform/src/test/java/org/apache/maven/surefire/junitplatform/JUnitPlatformProviderTest.java
This fixes the regression https://issues.apache.org/jira/browse/SUREFIRE-2143
- In executionSkipped handle ParameterizedTest which is a non-class test container the same as a regular test
- In executionSkipped always remove the testIdentifier from the map testStartTime, regardless if it's a class or a test
- In createReportEntry set methodName and methodText if the testExecutionResult is null, which is the case for skipped tests, otherwise the test name in the XML report is left empty
- Add ITs also for the related previous issue SUREFIRE-2032 the fix of which caused this regression, to make sure that fix still works
for the change (usually before you start working on it).  Trivial changes like typos do …
> [SUREFIRE-2143] Fix reporting of skipped parameterized test

- maven-failsafe-plugin/src/main/java/org/apache/maven/plugin/failsafe/IntegrationTestMojo.java
Surefire is using `surefire.failIfNoSpecifiedTests`, but failsafe used `it.failIfNoSpecifiedTests`.
Error msg is then pointed to nonexistent property: `No tests matching pattern "..." were executed! (Set -Dfailsafe.failIfNoSpecifiedTests=false to ignore this error.)`
If your …
> [SUREFIRE-2119] - Sanitize failIfNoSpecifiedTests prefix in failsafe

- maven-surefire-common/pom.xml
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/AbstractSurefireMojo.java
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/SurefireDependencyResolver.java
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/SurefireExecutionParameters.java
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/booterclient/ChecksumCalculator.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/AbstractSurefireMojoTest.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/SurefireDependencyResolverTest.java
- not use org.apache.maven.artifact.repository.ArtifactRepository
- use resolver API
---
please ask on …
> [SUREFIRE-2154] Get rid of localRepository from surefire mojo parameter, use Resolver API

- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/report/StatelessXmlReporter.java
- surefire-report-parser/src/main/java/org/apache/maven/plugins/surefire/report/TestSuiteXmlParser.java
> Simplify serialization/deserialization of elapsed time (SUREFIRE-2164 + SUREFIRE-2167)

- maven-surefire-report-plugin/src/main/java/org/apache/maven/plugins/surefire/report/SurefireReportRenderer.java
- maven-surefire-report-plugin/src/main/resources/surefire-report.properties
- maven-surefire-report-plugin/src/main/resources/surefire-report_de.properties
- maven-surefire-report-plugin/src/main/resources/surefire-report_sv.properties
- maven-surefire-report-plugin/src/test/java/org/apache/maven/plugins/surefire/report/Surefire597Test.java
- maven-surefire-report-plugin/src/test/java/org/apache/maven/plugins/surefire/report/SurefireReportMojoTest.java
> [SUREFIRE-2166] Use ChoiceFormat to selective render percentage and elapsed time in SurefireReportRenderer

- pom.xml
Looks like we can get rid of this one. Let's see...
> Remove old junittoolbox dependency no longer used

- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/AbstractSurefireMojo.java
For fork starter log the underlying configuration class name as well
please ask on the developers …
> [SUREFIRE-2182] Log starter implementation on DEBUG level

- pom.xml
See [SUREFIRE-2177](https://issues.apache.org/jira/browse/SUREFIRE-2177).
> [SUREFIRE-2177] Use junit-bom instead of single JUnit 5 versions

- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/AbstractSurefireMojoTest.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/util/DependenciesScannerTest.java
- maven-surefire-common/src/test/java/org/apache/maven/surefire/report/FileReporterTest.java
- surefire-booter/src/main/java/org/apache/maven/surefire/booter/SurefireReflector.java
- surefire-booter/src/test/java/org/apache/maven/surefire/booter/SurefireReflectorTest.java
- surefire-its/src/test/java/org/apache/maven/surefire/its/fixture/OutputValidator.java
- surefire-its/src/test/resources/surefire-1179-testng-parallel-dataprovider/src/test/java/debug/ParallelTest.java
- surefire-providers/surefire-junit4/src/test/java/org/apache/maven/surefire/junit4/JUnit4ProviderTest.java
- surefire-providers/surefire-junit47/src/main/java/org/apache/maven/surefire/junitcore/AsynchronousRunner.java
- surefire-providers/surefire-junit47/src/main/java/org/apache/maven/surefire/junitcore/ConfigurableParallelComputer.java
- surefire-providers/surefire-junit47/src/main/java/org/apache/maven/surefire/junitcore/pc/SharedThreadPoolStrategy.java
As discussed on
- https://github.com/apache/maven-scm/pull/184
- https://issues.apache.org/jira/browse/MNG-6847
Use this link to re-run the recipe: https://app.moderne.io/recipes/org.openrewrite.staticanalysis.UseDiamondOperator?organizationId=QXBhY2hlIE1hdmVu
----
If your pull …
> [MNG-6847] Use diamond operator

- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/booterclient/ModularClasspathForkConfiguration.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/booterclient/ForkConfigurationTest.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/booterclient/ModularClasspathForkConfigurationTest.java
- surefire-its/src/test/java/org/apache/maven/surefire/its/jiras/Surefire2190JUnitIT.java
- surefire-its/src/test/resources/surefire-2190/pom.xml
- surefire-its/src/test/resources/surefire-2190/src/main/java/module-info.java
- surefire-its/src/test/resources/surefire-2190/src/main/java/surefirebug/thing/Main.java
- surefire-its/src/test/resources/surefire-2190/src/test/java/surefirebug/thing/MainTest.java
Include all modules on the module path to the root modules. This fixes
test code that uses dependencies that are declared as optional
(`require static`) for the main artifact to access these dependencies.
maven surefire plugin struggles with optional dependencies for the main artifact and test code.
Check out the test repo at https://github.com/hgschmie/msurefire2190
This repo contains three artifacts with identical code:
- thing1 builds a main artifact without JPMS
- thing2 builds a main artifact with a strong (`requires`) dependency on jakarta.annotation.
- thing3 builds a main artifact with a compile-only (`requires static`) dependency on jakarta annotations.
The code and its test classes are otherwise identical.
Running `mvn -DskipTests clean install` builds all three modules and the …
> [SUREFIRE-2190] Fix module dependencies for compile only dependencies

- maven-surefire-plugin/src/site/apt/examples/testng.apt.vm
`http://www.testng.org` does not work anymore. Changed to `https://testng.org`
> Fix TestNG web site URL

- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/booterclient/DefaultForkConfiguration.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/booterclient/ForkConfigurationTest.java
- maven-surefire-plugin/src/site/apt/examples/fork-options-and-parallel-execution.apt.vm
Implementation for https://issues.apache.org/jira/browse/SUREFIRE-1124 including test and documentation updates. I also changed "place holder" to "placeholder" in the related documentation section as this is the common way to write it.
Thank you for having a look at this PR!
I hereby declare this contribution to be licenced under the Apache License Version 2.0, January 2004
> [SUREFIRE-1124] Support forkNumber in environment variables

- maven-failsafe-plugin/pom.xml
- maven-surefire-plugin/pom.xml
- maven-surefire-report-plugin/pom.xml
- pom.xml
> [SUREFIRE-2205] Use maven-plugin-report-plugin only in plugins modules

- maven-surefire-plugin/src/site/apt/examples/toolchains.apt.vm
This was triggered by https://issues.apache.org/jira/browse/SUREFIRE-1923?focusedCommentId=17795866&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17795866
> [SUREFIRE-2221] Document minimum supported Java version for Toolchains

- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/report/StatelessXmlReporter.java
> [SUREFIRE-2224] StatelessXmlReporter#getTestProblems() does not properly reflect report schema structure 

- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/AbstractSurefireMojo.java
This closes #703
To make clear that you license your contribution …
> [SUREFIRE-2223] Surefire evaluates parameter jvm before skip

- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/report/DefaultReporterFactory.java
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/report/StatelessXmlReporter.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/report/DefaultReporterFactoryTest.java
> Use uppercase convention for enum member names

- surefire-its/src/test/java/org/apache/maven/surefire/its/fixture/SurefireLauncher.java
- surefire-its/src/test/resources/junit47-parallel/pom.xml
- surefire-its/src/test/resources/testng-740-parallel-without-threadcount/pom.xml
- surefire-its/src/test/resources/testng-740-parallel/pom.xml
- surefire-its/src/test/resources/testng-simple/pom.xml
This closes #705
To make clear that you license your contribution …
> [SUREFIRE-2225] Surefire ITs fail when project directory contains space

- pom.xml
- surefire-its/src/test/java/org/apache/maven/surefire/its/CheckTestNgVersionsIT.java
- surefire-its/src/test/java/org/apache/maven/surefire/its/jiras/Surefire1967CheckTestNgMethodParallelOrderingIT.java
> [SUREFIRE-2231] JaCoCo 0.8.11 fails with old TestNG releases on Java 17+

- maven-surefire-plugin/src/site/apt/examples/testng.apt.vm
TestNG 5 is circa 2010. Focus on what the current version does.
> Remove references to very old versions of surefire and TestNG

- maven-failsafe-plugin/pom.xml
- maven-surefire-common/pom.xml
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/AbstractSurefireMojo.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/AbstractSurefireMojoToolchainsTest.java
- maven-surefire-plugin/pom.xml
- maven-surefire-report-plugin/pom.xml
- pom.xml
- surefire-api/pom.xml
- surefire-booter/pom.xml
- surefire-extensions-api/pom.xml
- surefire-grouper/pom.xml
- surefire-its/pom.xml
- surefire-its/src/test/java/org/apache/maven/surefire/its/JUnitPlatformEnginesIT.java
- surefire-its/src/test/java/org/apache/maven/surefire/its/JUnitPlatformIT.java
- surefire-its/src/test/resources/junit-4-5/pom.xml
- surefire-its/src/test/resources/junit5-suite/pom.xml
- surefire-logger-api/pom.xml
- surefire-providers/common-java5/pom.xml
- surefire-providers/common-junit3/pom.xml
- surefire-providers/common-junit4/pom.xml
- surefire-providers/common-junit48/pom.xml
- surefire-providers/pom.xml
- surefire-providers/surefire-junit3/pom.xml
- surefire-providers/surefire-junit4/pom.xml
- surefire-providers/surefire-junit47/pom.xml
- surefire-providers/surefire-testng-utils/pom.xml
- surefire-providers/surefire-testng/pom.xml
- surefire-report-parser/pom.xml
> [SUREFIRE-2245] Upgrade to Parent 42 and Maven 3.6.3

- surefire-booter/src/test/java/org/apache/maven/surefire/booter/SystemUtilsTest.java
Removes an invalid test which passes a JDK or JRE home to a method which expects the path to the Java executable. Therefore the invalid input leads to an exception.
This closes #743
[Individual Contributor …
> [SUREFIRE-1939] Build fails if java.home has <=2 path components

- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/report/StatelessXmlReporter.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/report/StatelessXmlReporterTest.java
> A regression bug appeared in 3.0.0-M6:
>
> A testNG test class has a listener which updates results from SUCCESS to FAILURE:
``` java
@Override
public void onTestSuccess(ITestResult result) {
result.setStatus(ITestResult.FAILURE);
result.getTestContext().getPassedTests().removeResult(result);
result.getTestContext().getFailedTests().addResult(result);
}
```
> Surefire fails to process a failed test result without a throwable and reports 0 total tests. 
```
ForkStarter IOException: java.util.NoSuchElementException.
org.apache.maven.plugin.surefire.booterclient.output.MultipleFailureException: java.util.NoSuchElementException
at org.apache.maven.plugin.surefire.booterclient.output.ThreadedStreamConsumer$Pumper.<init>(ThreadedStreamConsumer.java:59)
at …
```
> [SUREFIRE-2232] StatelessXmlReporter: handle failed test result without a throwable

- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/AbstractSurefireMojo.java
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/CommonReflector.java
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/StartupReportConfiguration.java
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/extensions/DefaultStatelessReportMojoConfiguration.java
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/extensions/SurefireStatelessReporter.java
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/extensions/junit5/JUnit5Xml30StatelessReporter.java
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/report/NullStatelessXmlReporter.java
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/report/StatelessXmlReporter.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/CommonReflectorTest.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/booterclient/ForkStarterTest.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/booterclient/TestSetMockReporterFactory.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/extensions/StatelessReporterTest.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/report/DefaultReporterFactoryTest.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/report/StatelessXmlReporterTest.java
- maven-surefire-plugin/src/site/apt/examples/junit-platform.apt.vm
- maven-surefire-plugin/src/site/resources/xsd/surefire-test-report.xsd
- maven-surefire-report-plugin/src/test/resources/surefire-1894/TEST-surefire.MyTest.xml
- surefire-api/src/main/java/org/apache/maven/surefire/api/booter/ProviderParameterNames.java
- surefire-extensions-api/src/main/java/org/apache/maven/surefire/extensions/StatelessReportMojoConfiguration.java
- surefire-extensions-api/src/main/java/org/apache/maven/surefire/extensions/StatelessReporter.java
- surefire-its/src/test/java/org/apache/maven/surefire/its/jiras/Surefire1360PropertiesElementIT.java
- surefire-its/src/test/resources/surefire-1360-disable-properties-element/pom.xml
- surefire-its/src/test/resources/surefire-1360-disable-properties-element/src/test/java/disablePropertiesElement/TestPropertiesElement.java
- surefire-its/src/test/resources/surefire-1360-disable-properties-element/src/test/java/disablePropertiesElement/TestPropertiesElement2.java
- surefire-its/src/test/resources/surefire-1360-enable-properties-element/pom.xml
- surefire-its/src/test/resources/surefire-1360-enable-properties-element/src/test/java/enablePropertiesElement/TestPropertiesElement.java
- surefire-providers/surefire-junit47/src/main/java/org/apache/maven/surefire/junitcore/JUnitCoreParameters.java
- surefire-providers/surefire-junit47/src/test/java/org/apache/maven/surefire/junitcore/JUnitCoreParametersTest.java
- surefire-providers/surefire-junit47/src/test/java/org/apache/maven/surefire/junitcore/JUnitCoreTester.java
- surefire-report-parser/src/test/resources/fixture/testsuitexmlparser/TEST-org.acme.FlakyTest.xml
> [SUREFIRE-2250] Surefire Test Report Schema properties element is not consistent with the code

- maven-failsafe-plugin/src/main/java/org/apache/maven/plugin/failsafe/IntegrationTestMojo.java
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/AbstractSurefireMojo.java
- maven-surefire-plugin/src/main/java/org/apache/maven/plugin/surefire/SurefirePlugin.java
> javadoc: improve description of systemPropertyVariables

- maven-failsafe-plugin/src/main/java/org/apache/maven/plugin/failsafe/VerifyMojo.java
The failsafe plugin's verify goal description states it works against test previously run by Surefire, this should say Failsafe instead. …
> [Doc] Failsafe Verify goal should mention failsafe

- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/SurefireHelper.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/SurefireHelperTest.java
- maven-surefire-plugin/src/test/java/org/apache/maven/plugin/surefire/SurefireMojoTest.java
- surefire-api/src/main/java/org/apache/maven/surefire/api/util/RunOrder.java
- surefire-providers/surefire-junit47/src/main/java/org/apache/maven/surefire/junitcore/AsynchronousRunner.java
- surefire-providers/surefire-junit47/src/main/java/org/apache/maven/surefire/junitcore/ConfigurableParallelComputer.java
- surefire-providers/surefire-junit47/src/main/java/org/apache/maven/surefire/junitcore/SynchronousRunner.java
"Please" is generally not best practice in computer UI messages. 
Locally tests failed in a way that suggests `mvn clean test` is insufficient to build this project. Let's see what the CI says.
> [SUREFIRE-2278] Don't say please.

- surefire-api/src/main/java/org/apache/maven/surefire/api/util/RunOrder.java
A trivial optimization because I was bored. This class should really be an enum, but legacy code and all that. Might be an even cleaner way to do this nowadays.
> Reduce cyclomatic complexity

- maven-failsafe-plugin/pom.xml
- maven-surefire-common/pom.xml
- pom.xml
- surefire-api/pom.xml
- surefire-booter/pom.xml
- surefire-extensions-api/pom.xml
- surefire-providers/common-java5/pom.xml
- surefire-providers/common-junit4/pom.xml
- surefire-providers/common-junit48/pom.xml
- surefire-providers/surefire-junit-platform/pom.xml
- surefire-providers/surefire-junit3/pom.xml
- surefire-providers/surefire-testng/pom.xml
> move this dependency to dptMngt

- surefire-providers/surefire-junit-platform/src/main/java/org/apache/maven/surefire/junitplatform/JUnitPlatformProvider.java
- surefire-providers/surefire-junit-platform/src/test/java/org/apache/maven/surefire/junitplatform/JUnitPlatformProviderTest.java
[This PR](https://github.com/apache/maven-surefire/pull/863) introduces a change in the `JUnitPlatformProvider` class, which causes the output of registered [LauncherSessionListeners](https://docs.junit.org/current/api/org.junit.platform.launcher/org/junit/platform/launcher/LauncherSessionListener.html#launcherSessionOpened(org.junit.platform.launcher.LauncherSession)) during opening a JUnit launcher session to not be captured anymore. The reason for this bug is that the launcher session is opened before output capturing has started.
This PR aims to fix this by starting with output capturing before the JUnit launcher session is actually opened.
The PR also contains an adjusted `JUnitPlatformProviderTest.outputIsCaptured()` that verifies the output capturing of launcher session listeners. …
> Fix capturing of output of JUnit `LauncherSessionListener`
