apache/maven-surefire

- surefire-integration-tests/src/test/java/org/apache/maven/surefire/its/jiras/Surefire1152RerunFailingTestsInSuiteIT.java
- surefire-integration-tests/src/test/resources/surefire-1152-rerunFailingTestsCount-suite/pom.xml
- surefire-integration-tests/src/test/resources/surefire-1152-rerunFailingTestsCount-suite/src/test/java/jiras/surefire1152/FlakyIT.java
- surefire-integration-tests/src/test/resources/surefire-1152-rerunFailingTestsCount-suite/src/test/java/jiras/surefire1152/FlakyITSuite.java
- surefire-integration-tests/src/test/resources/surefire-1152-rerunFailingTestsCount-suite/src/test/java/jiras/surefire1152/FlakyParent.java
- surefire-integration-tests/src/test/resources/surefire-1152-rerunFailingTestsCount-suite/src/test/java/jiras/surefire1152/FlakyTest.java
- surefire-integration-tests/src/test/resources/surefire-1152-rerunFailingTestsCount-suite/src/test/java/jiras/surefire1152/FlakyTestSuite.java
- surefire-providers/common-junit4/src/main/java/org/apache/maven/surefire/common/junit4/JUnit4ProviderUtil.java
- surefire-providers/common-junit4/src/test/java/org/apache/maven/surefire/common/junit4/JUnit4ProviderUtilTest.java
- surefire-providers/surefire-junit4/src/main/java/org/apache/maven/surefire/junit4/JUnit4Provider.java
- surefire-providers/surefire-junit47/src/main/java/org/apache/maven/surefire/junitcore/JUnitCoreProvider.java
> [SUREFIRE-1152] Support rerunFailingTestsCount for test suites

- pom.xml
Fix link in accordance with [SUREFIRE-1173](https://issues.apache.org/jira/browse/SUREFIRE-1173)
> [SUREFIRE-1173] Fix redirected link on plugin's website

- surefire-integration-tests/src/test/resources/junit4/pom.xml
> Make JUnit4VersionsIT acutally use the versions set by the test code

- maven-surefire-plugin/src/site/apt/examples/fork-options-and-parallel-execution.apt.vm
Resolves [SUREFIRE-1301](https://issues.apache.org/jira/browse/SUREFIRE-1301).
> [SUREFIRE-1301] add note for changing system properties when running parallel builds with disabled forking

- surefire-providers/pom.xml
This PR fixes the JUnit5 module name `surefire-junit-platform` in the `surefire-providers` POM reactor.
<details>
<summary>Build logs results with and without the fix</summary>
Indeed, without this PR I can't build the project on this branch:
```
╭─mgreau@mbpro ~/GIT/mgreau/maven-surefire  ‹3.0-rc1› 
╰─$ mvn clean install
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Child module /Users/mgreau/Dev/Sources/eXo/all_git_repos/mgreau/maven-surefire/surefire-providers/surefire-junit5 of /Users/mgreau/Dev/Sources/eXo/all_git_repos/mgreau/maven-surefire/surefire-providers/pom.xml does not exist @ 
@ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project …
```
> SUREFIRE-1330: Fix module name in surefire-providers reactor

- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/AbstractSurefireMojo.java
- surefire-integration-tests/src/test/java/org/apache/maven/surefire/its/JUnitPlattformIT.java
- surefire-integration-tests/src/test/resources/junit-plattform/pom.xml
- surefire-integration-tests/src/test/resources/junit-plattform/src/test/java/junitplattform/BasicTest.java
Followup for #153 
This is Work in Progress! First take on a JUnitPlattform ProviderInfo, to enable automatic provider lookup.
Need help to get things working :)
> SUREFIRE-1384: ProviderInfo for JUnit Plattform (WIP)

- maven-surefire-report-plugin/src/main/java/org/apache/maven/plugins/surefire/report/AbstractSurefireReportMojo.java
- maven-surefire-report-plugin/src/main/java/org/apache/maven/plugins/surefire/report/FailsafeReportMojo.java
- maven-surefire-report-plugin/src/main/java/org/apache/maven/plugins/surefire/report/LocalizedProperties.java
- maven-surefire-report-plugin/src/main/java/org/apache/maven/plugins/surefire/report/SurefireReportGenerator.java
- maven-surefire-report-plugin/src/main/java/org/apache/maven/plugins/surefire/report/SurefireReportMojo.java
- maven-surefire-report-plugin/src/main/resources/surefire-report.properties
- maven-surefire-report-plugin/src/main/resources/surefire-report_de.properties
- maven-surefire-report-plugin/src/main/resources/surefire-report_sv.properties
- maven-surefire-report-plugin/src/test/java/org/apache/maven/plugins/surefire/report/Surefire597Test.java
- surefire-its/src/test/java/org/apache/maven/surefire/its/jiras/Surefire1490ReportTitleDescriptionIT.java
- surefire-its/src/test/resources/surefire-1490/pom.xml
- surefire-its/src/test/resources/surefire-1490/src/test/java/it/Surefire1490IT.java
- surefire-its/src/test/resources/surefire-1490/src/test/java/it/Surefire1490Test.java
Related to JIRA [SUREFIRE-1490](https://issues.apache.org/jira/browse/SUREFIRE-1490).
> [SUREFIRE-1490] Change header of the Failsafe Report

- maven-surefire-plugin/src/site/resources/xsd/surefire-test-report.xsd
- maven-surefire-report-plugin/pom.xml
- maven-surefire-report-plugin/src/test/java/org/apache/maven/plugins/surefire/report/SurefireSchemaValidationTest.java
rerun element
Add missing XSD elements generated by the rerun feature.
> [SUREFIRE-1550] The surefire XSD published on maven site lacks of some

- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/AbstractSurefireMojo.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/AbstractSurefireMojoJava7PlusTest.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/booterclient/ModularClasspathForkConfigurationTest.java
- surefire-booter/src/main/java/org/apache/maven/surefire/booter/AbstractPathConfiguration.java
- surefire-booter/src/main/java/org/apache/maven/surefire/booter/ModularClasspathConfiguration.java
- surefire-its/src/test/java/org/apache/maven/surefire/its/AbstractJigsawIT.java
- surefire-its/src/test/java/org/apache/maven/surefire/its/Java9FullApiIT.java
- surefire-its/src/test/java/org/apache/maven/surefire/its/ModulePathIT.java
- surefire-its/src/test/java/org/apache/maven/surefire/its/jiras/Surefire1265Java9IT.java
- surefire-its/src/test/java/org/apache/maven/surefire/its/jiras/Surefire1534ReuseForksFalseWithJavaModuleIT.java
- surefire-its/src/test/resources/surefire-1534-reuse-forks-false-java-module/pom.xml
- surefire-its/src/test/resources/surefire-1534-reuse-forks-false-java-module/src/main/java/it/Main.java
- surefire-its/src/test/resources/surefire-1534-reuse-forks-false-java-module/src/main/java/module-info.java
- surefire-its/src/test/resources/surefire-1534-reuse-forks-false-java-module/src/test/java/it/MainTest.java
- surefire-providers/surefire-junit-platform/src/main/java/org/apache/maven/surefire/junitplatform/RunListenerAdapter.java
A fix with IT for SUREFIRE-1534.
> Surefire 1534

- surefire-its/src/test/java/org/apache/maven/surefire/its/PojoSimpleIT.java
- surefire-its/src/test/resources/pojo-simple/src/test/java/PojoTest.java
- surefire-providers/surefire-junit3/src/main/java/org/apache/maven/surefire/junit/JUnit3Provider.java
- surefire-providers/surefire-junit3/src/main/java/org/apache/maven/surefire/junit/PojoTestSet.java
> [SUREFIRE-1669] POJO tests do not call fixture methods setUp and tearDown and test instance are not new between tests

- maven-surefire-plugin/src/site/apt/index.apt.vm
- maven-surefire-report-plugin/src/site/apt/index.apt
Removes wiki link described in this JIRA and discussed on dev chat
> [SUREFIRE-1664] Remove deadlink to wiki

- maven-failsafe-plugin/src/main/java/org/apache/maven/plugin/failsafe/util/FailsafeSummaryXmlUtils.java
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/SurefireProperties.java
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/booterclient/output/ForkClient.java
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/booterclient/output/ForkedChannelDecoder.java
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/report/FileReporter.java
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/report/StatelessXmlReporter.java
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/report/WrappedReportEntry.java
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/util/FileScanner.java
- surefire-api/src/main/java/org/apache/maven/surefire/booter/Command.java
- surefire-api/src/main/java/org/apache/maven/surefire/booter/CommandReader.java
- surefire-api/src/main/java/org/apache/maven/surefire/util/internal/ClassMethod.java
- surefire-api/src/main/java/org/apache/maven/surefire/util/internal/StringUtils.java
- surefire-booter/src/main/java/org/apache/maven/surefire/booter/ProcessCheckerType.java
- surefire-booter/src/main/java/org/apache/maven/surefire/booter/PropertiesWrapper.java
- surefire-booter/src/main/java/org/apache/maven/surefire/booter/SurefireBooterForkException.java
- surefire-extensions-api/src/main/java/org/apache/maven/surefire/extensions/ConsoleOutputReporter.java
- surefire-extensions-api/src/main/java/org/apache/maven/surefire/extensions/StatelessReporter.java
- surefire-providers/common-junit4/src/main/java/org/apache/maven/surefire/common/junit4/JUnit4RunListenerFactory.java
- surefire-providers/common-junit48/src/main/java/org/apache/maven/surefire/common/junit48/FilterFactory.java
- surefire-providers/surefire-testng/src/main/java/org/apache/maven/surefire/testng/TestNGDirectoryTestSuite.java
- surefire-providers/surefire-testng/src/main/java/org/apache/maven/surefire/testng/TestNGExecutor.java
Use org.apache.maven.surefire.shared.utils.StringUtils instead.
> Delete is{Not}Blank from internal StringUtils

- .github/workflows/maven.yml
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/report/StatelessXmlReporter.java
- surefire-its/src/test/java/org/apache/maven/surefire/its/jiras/Surefire1744AlwaysIncludeOutputLogsIT.java
- surefire-its/src/test/resources/surefire-1744-alwaysIncludeOutputLogs/pom.xml
- surefire-its/src/test/resources/surefire-1744-alwaysIncludeOutputLogs/src/main/resources/log4j.properties
- surefire-its/src/test/resources/surefire-1744-alwaysIncludeOutputLogs/src/test/java/alwaysIncludeOutputLogs/TestSurefire3.java
Original Tickete at : https://issues.apache.org/jira/projects/SUREFIRE/issues/SUREFIRE-1744?filter=allopenissues
> SUREFIRE-1744 - enable system-out for successful tests as well

- maven-surefire-plugin/src/site/fml/faq.fml
> docs: codehaus is defunct

- pom.xml
[* ] I hereby declare this contribution to be licenced under the Apache License Version 2.0, January 2004
> [SUREFIRE-1754] Upgrade Doxia and Doxia Site Tools to remove struts

- surefire-providers/surefire-testng/src/main/java/org/apache/maven/surefire/testng/TestNGExecutor.java
Reverts apache/maven-surefire#276
> Revert "use org.testng.TestNG.addListener(java.lang.Object)"

- pom.xml
> deps: update parent POM

- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/booterclient/lazytestprovider/OutputStreamFlushableCommandline.java
> SUREFIRE-1782 Exclude explicitly configured env vars

- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/AbstractSurefireMojo.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/AbstractSurefireMojoTest.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/AbstractSurefireMojoToolchainsTest.java
Similar to #288 but for the jvm parameter.
> SUREFIRE-1784 Fork JVM defined by jvm param should not inherit JAVA_HOME from Maven process

- maven-surefire-plugin/src/site/apt/examples/jpms.apt.vm
found a typo in the example regarding hamcrest version
> version typo

- surefire-its/src/test/java/org/apache/maven/surefire/its/JUnitPlatformEnginesIT.java
- surefire-its/src/test/resources/surefire-1857-assertion-message/pom.xml
- surefire-its/src/test/resources/surefire-1857-assertion-message/src/test/java/jira1857/AssertionFailureMessageTest.java
- surefire-its/src/test/resources/surefire-1857-exception-message/pom.xml
- surefire-its/src/test/resources/surefire-1857-exception-message/src/test/java/jira1857/ExceptionMessageTest.java
- surefire-providers/surefire-junit-platform/src/main/java/org/apache/maven/surefire/junitplatform/RunListenerAdapter.java
Added exception message to report  
Added IT
> SUREFIRE-1857: JUnit 5 report does not contain assertion failure message

- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/AbstractSurefireMojo.java
Continuing https://github.com/apache/maven-surefire/pull/326/...
> Fix message about forkCount parameter = 0 - part 2

- maven-surefire-plugin/src/site/markdown/multilineexceptions.md
> docs: fix typo

- Jenkinsfile
Improvement in Jenkins build
- set stage status
- checkout scm in build stage
---
please ask on the …
> Jenkins build Improvement

- pom.xml
> [SUREFIRE-1974] Upgrade plexus-java to Version 1.1.0

- .github/workflows/maven-verify.yml
> GitHub Shared Action v2

- surefire-its/pom.xml
> Use the latest release version of failsafe in ITs

- maven-surefire-common/src/main/java/org/apache/maven/surefire/providerapi/ProviderDetector.java
> [SUREFIRE-1987] Refactor ProviderDetector

- .github/workflows/maven-verify.yml
> Drop max-parallel from GitHub build

- surefire-its/src/test/java/org/apache/maven/surefire/its/jiras/Surefire2006ShadefireTransformersIT.java
- surefire-its/src/test/resources/surefire-2006-shadefire-transformers/pom.xml
- surefire-its/src/test/resources/surefire-2006-shadefire-transformers/src/test/java/PojoTest.java
- surefire-shadefire/pom.xml
- surefire-shadefire/src/main/resources/META-INF/services/org.apache.maven.shadefire.surefire.spi.MasterProcessChannelProcessorFactory
- surefire-shadefire/src/main/resources/META-INF/services/org.apache.maven.surefire.api.provider.SurefireProvider
> [SUREFIRE-2006] Don't use Services Transformer in shadefire

- .github/release-drafter.yml
- .github/workflows/release-drafter.yml
> Add release-drafter to create gh releases

- Jenkinsfile
> Test only with 2 last Maven core 3.6.x and 3.8.x, avoid deep scanning to find jacoco files

- Jenkinsfile
> no need to notify build failure for working branch this generate a lot of noise

- .github/workflows/maven-verify.yml
According to https://github.com/apache/maven-gh-actions-shared/pull/40
---
please ask on the …
> Stage site on GH actions

- surefire-api/src/main/java/org/apache/maven/surefire/api/testset/TestListResolver.java
> [SUREFIRE-2042] Remove unused method TestListResolver#getWildcard

- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/AbstractSurefireMojo.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/AbstractSurefireMojoJava7PlusTest.java
> [SUREFIRE-2057] jpms requires static must be included

- pom.xml
> [SUREFIRE-2081] Upgrade Parent to 36

- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/report/StatelessXmlReporter.java
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/report/TestSetRunListener.java
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/report/Utf8RecodingDeferredFileOutputStream.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/report/StatelessXmlReporterTest.java
Some explanation for #531 .
To make clear that you license your …
> [SUREFIRE-2082] Close file handles asap to prevent breaching the system's maximum number of open files

- maven-surefire-report-plugin/src/main/java/org/apache/maven/plugins/surefire/report/AbstractSurefireReportMojo.java
> [SUREFIRE-2100] - make aggregate parameter work for single-module projects

- surefire-its/src/test/java/org/apache/maven/surefire/its/UmlautDirIT.java
In the UmlautDirIT two special directories are created that have a colon character in the name. This causes problems with the artifact upload of the Github actions, so we rename those directories at the end of the test to something without a colon character in it.
If your pull …
> [SUREFIRE-2136] Rename test dir that contains colon

- maven-failsafe-plugin/pom.xml
- maven-surefire-common/pom.xml
- maven-surefire-plugin/pom.xml
- maven-surefire-report-plugin/pom.xml
- pom.xml
- surefire-api/pom.xml
- surefire-booter/pom.xml
- surefire-extensions-api/pom.xml
- surefire-grouper/pom.xml
- surefire-its/pom.xml
- surefire-logger-api/pom.xml
- surefire-providers/common-java5/pom.xml
- surefire-providers/common-junit3/pom.xml
- surefire-providers/common-junit4/pom.xml
- surefire-providers/common-junit48/pom.xml
- surefire-providers/pom.xml
- surefire-providers/surefire-junit-platform/pom.xml
- surefire-providers/surefire-junit3/pom.xml
- surefire-providers/surefire-junit4/pom.xml
- surefire-providers/surefire-junit47/pom.xml
- surefire-providers/surefire-testng-utils/pom.xml
- surefire-providers/surefire-testng/pom.xml
- surefire-report-parser/pom.xml
- surefire-shadefire/pom.xml
> [SUREFIRE-2126] Use the latest surefire version 3.0.0-M7 with self testing

- surefire-its/src/test/java/org/apache/maven/surefire/its/JUnitPlatformEnginesIT.java
- surefire-its/src/test/java/org/apache/maven/surefire/its/JUnitPlatformIT.java
- surefire-its/src/test/java/org/apache/maven/surefire/its/jiras/Surefire1914XmlReportingParameterizedTestIT.java
- Add 5.8.2 and 5.9.1 to JUnitPlatformIT
- Add 5.7.2, 5.8.2 and 5.9.1 to JUnitPlatformEnginesIT
- Use most recent 5.6.x and 5.7.x patch versions in both
- Remove very old 5.0.3 and 5.1.1 from JUnitPlatformEnginesIT
- Simplify parameterization of SUREFIRE-1914-bugfix-verifying IT and run it against JUnit versions 5.2.0, 5.8.2 and 5.9.1 only, since it is just a bugfix-verifying IT after all
is to use the JIRA issue title in the …
> [SUREFIRE-2137] Run JUnitPlatform ITs with latest 5.8.x/5.9.x as well

- maven-surefire-report-plugin/src/main/java/org/apache/maven/plugins/surefire/report/SurefireReportGenerator.java
- maven-surefire-report-plugin/src/test/java/org/apache/maven/plugins/surefire/report/Surefire597Test.java
- surefire-api/src/test/java/org/apache/maven/surefire/api/testset/FundamentalFilterTest.java
> [SUREFIRE-2146] Don't draw border around reporting tables

- surefire-its/src/test/java/org/apache/maven/surefire/its/fixture/MavenLauncher.java
- surefire-its/src/test/resources/surefire-946-dummy-dependency/pom.xml
- surefire-its/src/test/resources/unicode-testnames/pom.xml
> [SUREFIRE-2149] Make all ITs run with Maven 3.9.0

- src/site/xdoc/download.xml.vm
> [SUREFIRE-2156] Refresh download page

- .gitattributes
> [SUREFIRE-2140] Cannot release Surefire on Windows

- pom.xml
> Drop unused commons-lang 2.6 from management

- pom.xml
various bug fixes: https://commons.apache.org/proper/commons-compress/changes-report.html#a1.23.0
> update commons compress to 1.23.0

- maven-failsafe-plugin/pom.xml
- maven-surefire-common/pom.xml
- pom.xml
> [SUREFIRE-2206] Downgrade plexus-xml to 3.0.0

- maven-failsafe-plugin/pom.xml
- maven-surefire-common/pom.xml
- maven-surefire-plugin/pom.xml
- maven-surefire-report-plugin/pom.xml
- pom.xml
- surefire-api/pom.xml
- surefire-booter/pom.xml
- surefire-extensions-api/pom.xml
- surefire-grouper/pom.xml
- surefire-its/pom.xml
- surefire-logger-api/pom.xml
- surefire-providers/common-java5/pom.xml
- surefire-providers/common-junit3/pom.xml
- surefire-providers/common-junit4/pom.xml
- surefire-providers/common-junit48/pom.xml
- surefire-providers/pom.xml
- surefire-providers/surefire-junit3/pom.xml
- surefire-providers/surefire-junit4/pom.xml
- surefire-providers/surefire-junit47/pom.xml
- surefire-providers/surefire-testng-utils/pom.xml
- surefire-providers/surefire-testng/pom.xml
- surefire-report-parser/pom.xml
Look at the comments as well. I do not yet understand the failures.
> [SUREFIRE-2216] Upgrade plugins and components (in ITs)

- surefire-its/src/test/java/org/apache/maven/surefire/its/jiras/Surefire1295AttributeJvmCrashesToTestsIT.java
> [SUREFIRE-2244] Make IT for SUREFIRE-1295 reliable

- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/SurefireHelperTest.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/report/StatelessXmlReporterTest.java
- surefire-its/src/test/java/org/apache/maven/surefire/its/UmlautDirIT.java
> Directory, not folder

- maven-failsafe-plugin/src/main/java/org/apache/maven/plugin/failsafe/IntegrationTestMojo.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/extensions/StatelessReporterTest.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/report/StatelessXmlReporterTest.java
- maven-surefire-plugin/src/main/java/org/apache/maven/plugin/surefire/SurefirePlugin.java
- maven-surefire-plugin/src/test/java/org/apache/maven/plugin/surefire/SurefirePluginTest.java
- surefire-its/src/test/java/org/apache/maven/surefire/its/JUnitPlatformEnginesIT.java
> Fix schema locations in code which lead to 404

- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/util/DependenciesScannerTest.java
- pom.xml
> [SUREFIRE-2047] Upgrade to maven-common-artifact-filters 3.4.0

- surefire-its/src/test/resources/surefire-1490-custom/pom.xml
- surefire-its/src/test/resources/surefire-1490-default/pom.xml
- surefire-its/src/test/resources/surefire-260-testWithIdenticalNames/pom.xml
- surefire-its/src/test/resources/surefire-570-multipleReportDirectories/pom.xml
> Update MSITE and MPIR in a few ITs

- maven-failsafe-plugin/src/main/java/org/apache/maven/plugin/failsafe/IntegrationTestMojo.java
- surefire-api/src/main/java/org/apache/maven/surefire/api/suite/RunResult.java
> [SUREFIRE-2124] Avoid creating unnecessary target files for pom projects

- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/booterclient/output/ForkClient.java
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/booterclient/output/ThreadedStreamConsumer.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/booterclient/output/ThreadedStreamConsumerTest.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/extensions/E2ETest.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/extensions/EventConsumerThreadTest.java
- surefire-api/src/main/java/org/apache/maven/surefire/api/report/ReportEntry.java
- surefire-api/src/main/java/org/apache/maven/surefire/api/util/SureFireFileManager.java
- surefire-api/src/test/java/org/apache/maven/surefire/api/stream/AbstractStreamDecoderTest.java
- surefire-api/src/test/java/org/apache/maven/surefire/api/util/internal/AsyncSocketTest.java
- surefire-booter/src/test/java/org/apache/maven/surefire/booter/PpidCheckerTest.java
- surefire-its/src/test/resources/reporters/src/test/java/reporters/Test1.java
- surefire-its/src/test/resources/reporters/src/test/java/reporters/Test2.java
- surefire-its/src/test/resources/testng-parallel-with-annotations/src/test/java/testng/paralellwithannotations/TestNGParallelTest.java
- surefire-providers/surefire-junit47/src/test/java/org/apache/maven/surefire/junitcore/pc/ParallelComputerBuilderTest.java
- surefire-providers/surefire-junit47/src/test/java/org/apache/maven/surefire/junitcore/pc/ParallelComputerUtilTest.java
> Improve time units

- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/AbstractSurefireMojo.java
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/CommonReflector.java
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/StartupReportConfiguration.java
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/extensions/DefaultStatelessReportMojoConfiguration.java
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/extensions/SurefireStatelessReporter.java
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/extensions/junit5/JUnit5Xml30StatelessReporter.java
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/report/NullStatelessXmlReporter.java
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/report/StatelessXmlReporter.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/CommonReflectorTest.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/booterclient/ForkStarterTest.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/booterclient/TestSetMockReporterFactory.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/extensions/StatelessReporterTest.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/report/DefaultReporterFactoryTest.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/report/StatelessXmlReporterTest.java
- surefire-api/src/main/java/org/apache/maven/surefire/api/booter/ProviderParameterNames.java
- surefire-extensions-api/src/main/java/org/apache/maven/surefire/extensions/StatelessReportMojoConfiguration.java
- surefire-its/src/test/java/org/apache/maven/surefire/its/jiras/Surefire1360PropertiesElementIT.java
- surefire-its/src/test/resources/surefire-1360-disable-properties-element/pom.xml
- surefire-its/src/test/resources/surefire-1360-disable-properties-element/src/test/java/disablePropertiesElement/TestPropertiesElement.java
- surefire-its/src/test/resources/surefire-1360-disable-properties-element/src/test/java/disablePropertiesElement/TestPropertiesElement2.java
- surefire-its/src/test/resources/surefire-1360-enable-properties-element/pom.xml
- surefire-its/src/test/resources/surefire-1360-enable-properties-element/src/test/java/enablePropertiesElement/TestPropertiesElement.java
- surefire-providers/surefire-junit47/src/main/java/org/apache/maven/surefire/junitcore/JUnitCoreParameters.java
- surefire-providers/surefire-junit47/src/test/java/org/apache/maven/surefire/junitcore/JUnitCoreParametersTest.java
- surefire-providers/surefire-junit47/src/test/java/org/apache/maven/surefire/junitcore/JUnitCoreTester.java
> [SUREFIRE-1360] Ability to disable properties for successfully passed tests

- pom.xml
- src/config/checkstyle-suppressions.xml
This closes #770
To make clear that you license your contribution …
> [SUREFIRE-2256] Upgrade to Parent 43

- maven-failsafe-plugin/pom.xml
- maven-surefire-common/pom.xml
- maven-surefire-plugin/pom.xml
- maven-surefire-report-plugin/pom.xml
- pom.xml
- surefire-api/pom.xml
- surefire-booter/pom.xml
- surefire-extensions-api/pom.xml
- surefire-grouper/pom.xml
- surefire-its/pom.xml
- surefire-logger-api/pom.xml
- surefire-providers/common-java5/pom.xml
- surefire-providers/common-junit3/pom.xml
- surefire-providers/common-junit4/pom.xml
- surefire-providers/common-junit48/pom.xml
- surefire-providers/pom.xml
- surefire-providers/surefire-junit3/pom.xml
- surefire-providers/surefire-junit4/pom.xml
- surefire-providers/surefire-junit47/pom.xml
- surefire-providers/surefire-testng-utils/pom.xml
- surefire-providers/surefire-testng/pom.xml
- surefire-report-parser/pom.xml
https://issues.apache.org/jira/browse/SUREFIRE-2263
> [SUREFIRE-2263] Use the latest version of surefire for self build

- maven-failsafe-plugin/src/main/java/org/apache/maven/plugin/failsafe/util/FailsafeSummaryXmlUtils.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/AbstractSurefireMojoToolchainsTest.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/booterclient/BooterDeserializerProviderConfigurationTest.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/booterclient/BooterDeserializerStartupConfigurationTest.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/booterclient/ForkConfigurationTest.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/runorder/RunEntryStatisticsMapTest.java
- surefire-booter/src/main/java/org/apache/maven/surefire/booter/PpidChecker.java
- surefire-booter/src/test/java/org/apache/maven/surefire/booter/ForkedBooterTest.java
https://issues.apache.org/jira/browse/SUREFIRE-2264
> [SUREFIRE-2264] Limit usage of commons-io from surefire-shared-utils

- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/AbstractSurefireMojo.java
https://issues.apache.org/jira/browse/SUREFIRE-1737
> [SUREFIRE-1737] Fix disable in statelessTestsetReporter

- surefire-shadefire/pom.xml
- surefire-shared-utils/pom.xml
https://issues.apache.org/jira/browse/SUREFIRE-2267
> [SUREFIRE-2267] Packages for commons-codec should be relocated in surefire-shared-utils

- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/AbstractSurefireMojo.java
- surefire-its/src/test/java/org/apache/maven/surefire/its/jiras/Surefire2006ShadefireTransformersIT.java
- surefire-its/src/test/resources/surefire-2006-shadefire-transformers/pom.xml
- surefire-its/src/test/resources/surefire-2006-shadefire-transformers/src/test/java/JUnit4Test.java
- surefire-its/src/test/resources/surefire-2006-shadefire-transformers/src/test/java/JUnit5Test.java
- surefire-shadefire/pom.xml
- surefire-shadefire/src/main/resources/META-INF/services/org.apache.maven.surefire.api.provider.SurefireProvider
https://issues.apache.org/jira/browse/SUREFIRE-2270
> [SUREFIRE-2270] Use JUnit5 in surefire-shadefire

- surefire-its/pom.xml
https://issues.apache.org/jira/browse/SUREFIRE-2269
> [SUREFIRE-2269] Allow fail during clean in surefire-its

- maven-failsafe-plugin/src/main/java/org/apache/maven/plugin/failsafe/VerifyMojo.java
- maven-failsafe-plugin/src/test/java/org/apache/maven/plugin/failsafe/VerifyMojoTest.java
This one's going to take a few PRs.
> Guice injection

- .github/workflows/pr-automation.yml
- .github/workflows/release-drafter.yml
- .github/workflows/stale.yml
> Add GitHub Automation actions

- maven-failsafe-plugin/pom.xml
- maven-failsafe-plugin/src/main/java/org/apache/maven/plugin/failsafe/VerifyMojo.java
- maven-failsafe-plugin/src/test/java/org/apache/maven/plugin/failsafe/VerifyMojoTest.java
- maven-surefire-common/pom.xml
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/AbstractSurefireMojo.java
- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/log/PluginConsoleLogger.java
- maven-surefire-common/src/main/java/org/apache/maven/surefire/providerapi/ProviderDetector.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/AbstractSurefireMojoJava7PlusTest.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/AbstractSurefireMojoTest.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/AbstractSurefireMojoToolchainsTest.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/MojoMocklessTest.java
- maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/SurefireHelperTest.java
- maven-surefire-common/src/test/java/org/apache/maven/surefire/providerapi/ProviderDetectorTest.java
- maven-surefire-plugin/pom.xml
- maven-surefire-report-plugin/pom.xml
- pom.xml
* Replace org.codehaus.plexus.logging.Logger with org.slf4j.Logger.
* Change from injected Plexus logger to lookup SLF4J logger. …
> [SUREFIRE-2291] Change logger from Plexus to SLF4J

- maven-failsafe-plugin/pom.xml
- maven-surefire-common/pom.xml
- maven-surefire-plugin/pom.xml
- maven-surefire-report-plugin/pom.xml
- pom.xml
- surefire-api/pom.xml
- surefire-booter/pom.xml
- surefire-extensions-api/pom.xml
- surefire-grouper/pom.xml
- surefire-its/pom.xml
- surefire-logger-api/pom.xml
- surefire-providers/common-java5/pom.xml
- surefire-providers/surefire-junit-platform/pom.xml
- surefire-providers/surefire-testng/pom.xml
- surefire-report-parser/pom.xml
Dependencies should be declared where is needed
> Remove dependencies from root pom

- maven-surefire-plugin/src/site/site.xml
- maven-surefire-report-plugin/src/site/site.xml
- src/site/site.xml
- surefire-api/src/site/site.xml
- surefire-providers/src/site/site.xml
> Update site descriptors

- pom.xml
- **surefire-shared-utils.version to 3.5.2**
- **no need of this extra property**
please ask on the …
> surefire shared utils version current version

- surefire-providers/surefire-junit-platform/pom.xml
> assertj-core must be test scope

- .github/pull_request_template.md
> no more Jira in pr template

- maven-failsafe-plugin/pom.xml
- maven-surefire-plugin/pom.xml
- maven-surefire-report-plugin/pom.xml
- pom.xml
As discussed in #846, we want to remove the maven-changes-plugin because we will have a release notes on GitHub. Therefore, a generated report about solved issues is not needed anymore.
> Remove maven-changes-plugin

- maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/AbstractSurefireMojo.java
> Name the shutdown hook

- .github/workflows/maven-verify.yml
- surefire-its/src/test/resources/cucumber-tests/pom.xml
> Simplify cuncumber IT configuration and make windows build working again
